### ISSUE TITLE
Error on datacats install - reload step

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#125]
Looks like install isn't passing a new parameter to reload
```
Traceback (most recent call last):
  File "/Users/dz/Envs/datacats/bin/datacats", line 9, in <module>
    load_entry_point('datacats==1.0.0dev1', 'console_scripts', 'datacats')()
  File "/Users/dz/source/datacats/datacats/cli/main.py", line 75, in main
    return command_fn(environment, opts)
  File "/Users/dz/source/datacats/datacats/cli/install.py", line 39, in install
    '--background': False})
  File "/Users/dz/source/datacats/datacats/cli/manage.py", line 77, in reload_
    if opts['PORT'] or opts['--address'] != '127.0.0.1':
KeyError: '--address'
```

**Comment by wardi** [comment]
we should add `datacats install` to our circleci tests
