### ISSUE TITLE
datacats-lesscd should work anywhere within source directory

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#163]
```
$ cd myckan/ckan/
$ datacats-lesscd .
Traceback (most recent call last):
  File "/Users/dz/Envs/datacats/bin/datacats-lesscd", line 9, in <module>
    load_entry_point('datacats==1.0.0dev1', 'console_scripts', 'datacats-lesscd')()
  File "/Users/dz/source/datacats/datacats/cli/lesscd.py", line 43, in main
    observer.schedule(event_handler, less_path, recursive=True)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/watchdog-0.8.3-py2.7-macosx-10.9-intel.egg/watchdog/observers/fsevents.py", line 172, in schedule
    return BaseObserver.schedule(self, event_handler, path, recursive)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/watchdog-0.8.3-py2.7-macosx-10.9-intel.egg/watchdog/observers/api.py", line 290, in schedule
    timeout=self.timeout)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/watchdog-0.8.3-py2.7-macosx-10.9-intel.egg/watchdog/observers/fsevents.py", line 73, in __init__
    self.snapshot = DirectorySnapshot(watch.path, watch.is_recursive)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/watchdog-0.8.3-py2.7-macosx-10.9-intel.egg/watchdog/utils/dirsnapshot.py", line 207, in __init__
    st = stat(path)
OSError: [Errno 2] No such file or directory: './ckan/ckan/public/base/less'
```

**Comment by JackMc** [comment]
#164 should make this work :-)
