### ISSUE TITLE
broken enviroment.py:Environment.create_source

### ISSUE THREAD

**Issue by dborzov** [datacats/datacats#166]
I attempted to create a datacats environment on a new machine with the current `master` branch verison:
```sh
git clone ..datacats
pip install -e datacats
datacats pull
datacats create townenv
```
and got the following error message traceback:
```sh
Creating environment "townenv"....
Traceback (most recent call last):
  File "/j/venv-datacats/bin/datacats", line 9, in <module>
    load_entry_point('datacats==1.0.0.dev1', 'console_scripts', 'datacats')()
  File "/j/datacats/datacats/cli/main.py", line 81, in main
    return command_fn(opts)
  File "/j/datacats/datacats/cli/create.py", line 47, in create
    log_syslog=opts['--syslog']
  File "/j/datacats/datacats/cli/create.py", line 83, in create_environment
    fn()
  File "/j/datacats/datacats/environment.py", line 394, in create_source
    self.target)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/j/townenv/ckan/ckan/config/who.ini'
```

It seems the recent development broke the web_command call:
```python
    def create_source(self):
        """
        Populate ckan directory from preloaded image and copy
        who.ini and schema.xml info conf directory
        """
        web_command(
            command='/bin/cp -a /project/ckan /project_target/ckan',
            rw={self.target: '/project_target'},
            image=self._preload_image())
```
that copies an instance of ckanica onto the new enviroment's directory.
 
Also, we should catch exceptions like this and output a user-friendly error message.

**Comment by wardi** [comment]
huh. why didn't circleci catch this?

**Comment by dborzov** [comment]
i dunno. investigating this with `ipdb` at the moment, will let you guys know what is up

**Comment by dborzov** [comment]
Oh, it seems to have something to do with user permission rights for the project environment directory. 

The command works fine when called from home directory, but breaks for root `/j` directories with `+r+w` rights for the user who calls the datacats command.

Which user corresponds to writing permissions the boot2docker rw binds?

**Comment by dborzov** [comment]
Ok so it seems that when I install the datacats repo belongs to `wheels` (superusers) usergroup on MacOSX instead of `staff`, all kinds of weird errors occur. Don't try this at home, folks.

**Comment by wardi** [comment]
I think this is caused by boot2docker only mounting /Users into the vm. That prevents us from mounting any files outside /Users into our containers.

I suggest not installing datacats or your source directories outside /Users on OSX

![Doctor it hurts when I do this](http://lowres.jantoo.com/medical-complaint-stupid-moronic-doctors-stupidity-11800675_low.jpg)

**Comment by wardi** [comment]
So, yes let's fix our OSX install instructions to recommend installing into a python virtualenv

**Comment by JackMc** [comment]
:+1:

**Comment by dborzov** [comment]
Good catch! As you mentioned, running `boot2docker ssh mount`shows all the directories mounted to boot2dcokers' virtual machine and it shows that only /Users is mounted on Macs
