### ISSUE TITLE
shell containers also need to know about datapusher

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#179]
Encountered with #165 

```
datacats paster datapusher submit
Data in any datastore resource that isn't in their source files (e.g. data added using the datastore API) will be permanently lost. Are you sure you want to proceed? [y/n] y
Submitting 1 datastore resources
Submitting 7b8ae2ed-15ff-4c69-8003-75330aebdc33...
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/project/ckan/ckanext/datapusher/cli.py", line 21, in command
    self._submit_all()
  File "/project/ckan/ckanext/datapusher/cli.py", line 42, in _submit_all
    if datapusher_submit(None, data_dict):
  File "/project/ckan/ckan/logic/__init__.py", line 424, in wrapped
    result = _action(context, data_dict, **kw)
  File "/project/ckan/ckanext/datapusher/logic/action.py", line 105, in datapusher_submit
    raise p.toolkit.ValidationError(error)
ckan.logic.ValidationError: None - {'message': 'Could not connect to DataPusher.', 'details': "HTTPConnectionPool(host='datapusher', port=8800): Max retries exceeded with url: /job (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)"}
```

**Comment by JackMc** [comment]
Thanks

**Comment by deniszgonjanin** [comment]
No, thank-you :bow:

**Comment by JackMc** [comment]
This is fixed now (or should be)

**Comment by JackMc** [comment]
Re open if it persists?

**Comment by deniszgonjanin** [comment]
@JackMc thanks, works great
