### ISSUE TITLE
exceptions in exceptions hiding real traceback?

### ISSUE THREAD

**Issue by wardi** [datacats/datacats#190]
```
$ datacats reset .
Resetting...
Creating environment bare/primary from existing environment directory "bare".....
Initializing database----------------------------------------
datacats: problem was encountered:
Traceback (most recent call last):
  File "/home/ian/boxkite/venv/bin/datacats", line 9, in <module>
    load_entry_point('datacats==1.0.0dev1', 'console_scripts', 'datacats')()
  File "/home/ian/boxkite/git/datacats/datacats/cli/main.py", line 126, in main
    parent_exception=UndocumentedError(exc_info)))
  File "/home/ian/boxkite/git/datacats/datacats/cli/main.py", line 132, in _error_exit
    exception.pretty_print()
  File "/home/ian/boxkite/git/datacats/datacats/error.py", line 32, in pretty_print
    print self.message.format(*self.format_args)
ValueError: Single '}' encountered in format string
```

**Comment by JackMc** [comment]
What was the root cause of this exception, btw?

**Comment by dborzov** [comment]
uh, that is not good. looking into this

**Comment by wardi** [comment]
Here's another one
```
$ datacats init
Creating environment bare/primary from existing environment directory "bare".......
Installing ckan
Installing ckan requirements
Initializing database
Starting web server at http://127.0.0.1:5565/ ...
admin user password:
confirm password:
data----------------------------------------
datacats: problem was encountered:
Traceback (most recent call last):
  File "/home/ian/boxkite/venv/bin/datacats", line 9, in <module>
    load_entry_point('datacats==1.0.0dev1', 'console_scripts', 'datacats')()
  File "/home/ian/boxkite/git/datacats/datacats/cli/main.py", line 126, in main
    parent_exception=UndocumentedError(exc_info)))
  File "/home/ian/boxkite/git/datacats/datacats/cli/main.py", line 132, in _error_exit
    exception.pretty_print()
  File "/home/ian/boxkite/git/datacats/datacats/error.py", line 32, in pretty_print
    print self.message.format(*self.format_args)
KeyError: 'self'
```

**Comment by wardi** [comment]
from https://github.com/datacats/datacats/issues/193#issue-88476683

```
Initializing database
----------------------------------------
datacats: problem was encountered:
Traceback (most recent call last):
  File "/Users/dz/Envs/datacats/bin/datacats", line 9, in <module>
    load_entry_point('datacats==1.0.0dev1', 'console_scripts', 'datacats')()
  File "/Users/dz/source/datacats/datacats/cli/main.py", line 126, in main
    parent_exception=UndocumentedError(exc_info)))
  File "/Users/dz/source/datacats/datacats/cli/main.py", line 132, in _error_exit
    exception.pretty_print()
  File "/Users/dz/source/datacats/datacats/error.py", line 32, in pretty_print
    print self.message.format(*self.format_args)
IndexError: tuple index out of range
```

**Comment by wardi** [comment]
Maybe we should just remove the fancy exception hidin^W handling for now.

**Comment by JackMc** [comment]
Hm, could maybe do a fallback to normal printing if exception?

**Comment by dborzov** [comment]
It seems the problem was that self.message.format(format_args) is called two times: once during the Datacats.__init__, the second time in Datacats.__str__(). My bad :( This quick fix should be good enough.
