### ISSUE TITLE
There is a bug in this software somewhere

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#193]
`datacats init` on master

```
Initializing database
----------------------------------------
datacats: problem was encountered:
Traceback (most recent call last):
  File "/Users/dz/Envs/datacats/bin/datacats", line 9, in <module>
    load_entry_point('datacats==1.0.0dev1', 'console_scripts', 'datacats')()
  File "/Users/dz/source/datacats/datacats/cli/main.py", line 126, in main
    parent_exception=UndocumentedError(exc_info)))
  File "/Users/dz/source/datacats/datacats/cli/main.py", line 132, in _error_exit
    exception.pretty_print()
  File "/Users/dz/source/datacats/datacats/error.py", line 32, in pretty_print
    print self.message.format(*self.format_args)
IndexError: tuple index out of range
```

**Comment by JackMc** [comment]
Any other details on the context? :p

**Comment by JackMc** [comment]
I cannot reproduce this atm

**Comment by wardi** [comment]
duplicate of #190

**Comment by deniszgonjanin** [comment]
I'll poke around

**Comment by dborzov** [comment]
the same issue as that [one](https://github.com/datacats/datacats/issues/190), exception catcher fails while formatting error message. working on it
