### ISSUE TITLE
Issues with migrate

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#240]
It seems that a data container was lost somewhere, somehow - likely at some earlier point in time. `datacats migrate` expects the data container to exist, so the command fails?

Trace below. Likely an edge case, but logging it here anyway

```
$ datacats migrate
After this command, your environment will be converted to format version 2.
and will only work with datacats version exceeding and including 1.0.0.
This migration is necessary to support multiple sites within the same environment.
Your current site will be kept and will be named "primary".

Would you like to continue the migration? (y/n) [n]:y
Making sure that containers are stopped...
Doing conversion...
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats migrate

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

-----------------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/dz/source/datacats/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/Users/dz/source/datacats/datacats/cli/migrate.py", line 35, in migrate
    convert_environment(datadir, version, always_yes)
  File "/Users/dz/source/datacats/datacats/migrate.py", line 235, in convert_environment
    migration_func(datadir)
  File "/Users/dz/source/datacats/datacats/migrate.py", line 96, in _one_to_two
    'datacats_pgdata_' + env_name + '_' + new_site_name)
  File "/Users/dz/source/datacats/datacats/docker.py", line 282, in rename_container
    _docker.rename(old_name, new_name)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.2.2-py2.7.egg/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.2.2-py2.7.egg/docker/client.py", line 976, in rename
    self._raise_for_status(res)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.2.2-py2.7.egg/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 404 Client Error: Not Found ("no such id: datacats_pgdata_community")

----------------------------------------
```

**Comment by deniszgonjanin** [comment]
A follow-up `datacats migrate` returns a new error:

```
$ datacats migrate
After this command, your environment will be converted to format version 2.
and will only work with datacats version exceeding and including 1.0.0.
This migration is necessary to support multiple sites within the same environment.
Your current site will be kept and will be named "primary".

Would you like to continue the migration? (y/n) [n]:y
Making sure that containers are stopped...
Doing conversion...
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats migrate

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

----------------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/dz/source/datacats/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/Users/dz/source/datacats/datacats/cli/migrate.py", line 35, in migrate
    convert_environment(datadir, version, always_yes)
  File "/Users/dz/source/datacats/datacats/migrate.py", line 235, in convert_environment
    migration_func(datadir)
  File "/Users/dz/source/datacats/datacats/migrate.py", line 91, in _one_to_two
    clean_up=True
  File "/Users/dz/source/datacats/datacats/docker.py", line 183, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/migrate.sh /project/data /project/data/sites/primary files passwords.ini run solr
    Docker Error Log:
    files passwords.ini run solr

----------------------------------------
```

**Comment by JackMc** [comment]
Yes, the rename is done after the copy of the files so it will get confused.

**Comment by JackMc** [comment]
It is trying to rename the pgdata container to use the new format and that's why it fails

**Comment by JackMc** [comment]
Do you think there should be a more human-readable error for this? What should it say?

**Comment by deniszgonjanin** [comment]
I don't know. I wish I knew what happened to that data container. Hopefully it was a boot2docker death event. Apart from that, I don't think any action is necessary here. Feel free to close, we can re-open if there is another occurence

**Comment by JackMc** [comment]
Just a side note: I migrated the community repo Friday and it worked so I don't think it's a migration problem that got rid of the container

**Comment by deniszgonjanin** [comment]
@JackMc thanks, good to hear
