### ISSUE TITLE
datacats create breaks on install_postgis.sh not found

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#244]
* AWS t2.micro with 100 GB volume, formatted with btrfs, mounted at /mnt/btrsfsvol
* Linux 3.13.0-48-generic kernel, Ubuntu 14.04 LTS
* Docker's `var/lib/docker` is soft-linked into btrfs volume
* my datacats fork, up to date with datacats master at the time of this writing, commit 6e457de33daed050d44416330da1420d9abc9e1e
* Error thrown when running `datacats create (environment name)`:

```
Traceback (most recent call last):
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/cli/create.py", line 52, in create
    datapusher=not opts['--no-datapusher'],
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/cli/create.py", line 96, in create_environment
    log_syslog=log_syslog)
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/cli/create.py", line 214, in finish_init
    environment.install_postgis_sql()
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/environment.py", line 347, in install_postgis_sql
    links={self._get_container_name('postgres'): 'db'},
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/docker.py", line 172, in web_command
    volumes_from=volumes_from)
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/docker_py-1.2.3-py2.7.egg/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/docker_py-1.2.3-py2.7.egg/docker/client.py", line 1076, in start
    self._raise_for_status(res)
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/docker_py-1.2.3-py2.7.egg/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 404 Client Error: Not Found ("Cannot start container 6d3ab57f9055def2fb1d191172ca96f5748366468772e6181ba913473141825d: [8] System error: exec: "\"/scripts/install_postgis.sh\"": stat "/scripts/install_postgis.sh": no such file or directory")
```

`datacats install` installs dependencies fine, but of course `datacats run` falls over the non-existent postgis container.

I ran into this problem in another VM, where I was lagging behind datacats upstream master, but this time I'm up to date with master. Anyone else running into this?

**Comment by JackMc** [comment]
Thanks for the report. I'll try and reproduce this on my instance when I get into work

**Comment by florianm** [comment]
Tried again, latest datacats master, latest datacats images, empty data dir, no docker containers running.

Error: `/scripts/install_postgis.sh` not found (presumably inside the container).

Trace:
```
(datacats)florianm@ip-172-31-1-89:/var/www/projects/datacats$ datacats create modena
Creating environment "modena/primary"...........
Installing ckan
Installing ckanext-modenatheme
Installing datapusher
Installing ckan requirements
Installing datapusher requirements
Initializing database
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create modena

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:

Traceback (most recent call last):
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/cli/create.py", line 52, in create
    datapusher=not opts['--no-datapusher'],
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/cli/create.py", line 96, in create_environment
    log_syslog=log_syslog)
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/cli/create.py", line 214, in finish_init
    environment.install_postgis_sql()
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/environment.py", line 347, in install_postgis_sql
    links={self._get_container_name('postgres'): 'db'},
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/datacats-1.1.0.dev1-py2.7.egg/datacats/docker.py", line 172, in web_command
    volumes_from=volumes_from)
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/docker_py-1.2.3-py2.7.egg/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/docker_py-1.2.3-py2.7.egg/docker/client.py", line 1076, in start
    self._raise_for_status(res)
  File "/mnt/btrfsvol/www/virtualenvs/datacats/local/lib/python2.7/site-packages/docker_py-1.2.3-py2.7.egg/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 404 Client Error: Not Found ("Cannot start container 2f3247159fed7a1da830675467aec251e5670e2f278e3c6860fae4816a850290: [8] System error: exec: "\"/scripts/install_postgis.sh\"": stat "/scripts/install_postgis.sh": no such file or directory")

----------------------------------------
(datacats)me@aws:/var/www/projects/datacats$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
0c17407f2f61        datacats/solr       "/usr/share/tomcat6/   50 seconds ago      Up 48 seconds       8080/tcp            datacats_solr_modena_primary       
5e22b6acfb64        datacats/postgres   "/docker-entrypoint.   50 seconds ago      Up 49 seconds       5432/tcp            datacats_postgres_modena_primary   
```

Would be super cool if I could get around this problem before the local GovHack this weekend :-)

**Comment by JackMc** [comment]
Hi! Sorry we took so long to figure this out.

It looks like the currently suggested solution is to downgrade to Docker 1.6.0.

**Comment by JackMc** [comment]
Pending https://github.com/docker/docker/issues/14170

**Comment by JackMc** [comment]
Working on a fix for datacats, though

**Comment by JackMc** [comment]
According to https://github.com/docker/docker/pull/14264 the next Docker release is scheduled for tomorrow.

**Comment by JackMc** [comment]
And will contain the fix we want

**Comment by JackMc** [comment]
A fix is now in datacats/master

**Comment by florianm** [comment]
Thanks @JackMc for the fix! I ended up doing a source install for my [govhack](https://vimeo.com/132628186) demo. Looking forward to using datacats again!

**Comment by JackMc** [comment]
Slick demo! Hope to hear from you again

**Comment by florianm** [comment]
@JackMc cheers :-) just to confirm, datacats works on my end again after installing the latest datacats master, installing the latest docker via `wget -qO- https://get.docker.com/ | sh`, pulling datacats images again with `datacats pull` and creating a new environment. Thanks again for the fix!

**Comment by florianm** [comment]
And just like that, [http://govhack.yes-we-ckan.org/](http://govhack.yes-we-ckan.org/) is online and rocking. GovHack would have been less fun had it been that easy ;-)
