### ISSUE TITLE
Permissions error when creating a datacats instance

### ISSUE THREAD

**Issue by nknezevicsurrey** [datacats/datacats#256]
When I try to create my CKAN instance I get the error below.  OS is Ubuntu 12.04.5.

me@myserver:~$ sudo datacats create myinstance
[sudo] password for me:
Creating environment "surreyckan/primary"..........
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create myinstance
 
It is seems to be a bug.
Please report this issue to us by creating an issue ticket at
 
    https://github.com/datacats/datacats/issues
 
so that we would be able to look into that and fix the issue.
 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 53, in create
    datapusher=not opts['--no-datapusher'],
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 90, in create_environment
    fn()
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 315, in create_install_template_skin
    self.install_package_develop('ckanext-' + self.name + 'theme')
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 721, in install_package_develop
    stream_output=stream_output
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 736, in user_run_script
    stream_output=stream_output
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 769, in run_command
    commit=True, stream_output=stream_output)
  File "/usr/local/lib/python2.7/dist-packages/datacats/docker.py", line 172, in web_command
    volumes_from=volumes_from)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 20, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 776, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/dist-packages/docker/clientbase.py", line 102, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Cannot start container b696e8fd3965a5ca69240c72ff3d4d1453b6a3b08e5b27022a112314a5154be9: [8] System error: exec: "/scripts/run_as_user.sh": permission denied")

**Comment by wardi** [comment]
Thank you for the report, this does look like something new. We'll try to reproduce this and investigate as soon as we can. Since this is Ubuntu 12.04, would you just confirm: are you using the right kernel version and is docker working normally, e.g. can you run a simple command like
```bash
docker run -it datacats/web bash
```

Also, what is the output of
```bash
python -c'import datacats, os; os.system("ls -l %s/scripts" % datacats.__path__[0])'
```

**Comment by nknezevicsurrey** [comment]
Hi Ian,

I had to run both commands with sudo.  The first was successful and the second returns this:

gisadmin@devopendata01:~$ sudo python -c'import datacats, os; os.system("ls -l %s/scripts" % datacats.__path__[0])'
total 84
-rw-rw-r-- 1 root staff 292 Jul 10 14:00 adjust_devini.py
-rw-r--r-- 1 root staff 527 Jul 10 14:08 adjust_devini.pyc
-rw-rw-r-- 1 root staff 258 Jul 10 14:00 check_connectivity.sh
-rw-rw-r-- 1 root staff 310 Jul 10 14:00 clean_virtualenv.sh
-rw-rw-r-- 1 root staff 419 Jul 10 14:00 compile_less.sh
-rw-rw-r-- 1 root staff 129 Jul 10 14:00 datapusher.sh
-rw-rw-r-- 1 root staff  98 Jul 10 14:00 install_ckan_plugin.sh
-rw-rw-r-- 1 root staff  66 Jul 10 14:00 install_extra_packages.sh
-rw-rw-r-- 1 root staff 441 Jul 10 14:00 install_package.sh
-rw-rw-r-- 1 root staff 677 Jul 10 14:00 install_postgis.sh
-rw-rw-r-- 1 root staff 441 Jul 10 14:00 install_reqs.sh
-rw-rw-r-- 1 root staff 996 Jul 10 14:00 known_hosts
-rw-rw-r-- 1 root staff 346 Jul 10 14:00 migrate.sh
-rw-rw-r-- 1 root staff 298 Jul 10 14:00 paster_cd.sh
-rw-rw-r-- 1 root staff 394 Jul 10 14:00 paster.sh
-rw-rw-r-- 1 root staff 319 Jul 10 14:00 purge.sh
-rw-rw-r-- 1 root staff 372 Jul 10 14:00 run_as_user.sh
-rw-rw-r-- 1 root staff 424 Jul 10 14:00 shell.sh
-rw-rw-r-- 1 root staff  26 Jul 10 14:00 ssh_config
-rw-rw-r-- 1 root staff 678 Jul 10 14:00 update_add_admin.sh
-rw-rw-r-- 1 root staff 888 Jul 10 14:00 web.sh

Thank you for looking into this.

Cheers,

NENAD KNEZEVIC | GIS ANALYST

CITY OF SURREY
GIS Section
13450 104th Ave, Surrey, BC, Canada V3T 1V8
T 604.598.5845  www.surrey.ca

**Comment by JackMc** [comment]
I'm going to try and reproduce this in an Ubuntu 12.04 VM. Can you let me know the following?

* What kernel version are you running? (``uname -a``)
* What version of Docker are you running? (``docker -v``)
* What version of Datacats are you running? (``datacats -v`` in your virtualenv)

**Comment by nknezevicsurrey** [comment]
See below.

Thank you ☺

NENAD KNEZEVIC | GIS ANALYST

CITY OF SURREY
GIS Section
13450 104th Ave, Surrey, BC, Canada V3T 1V8
T 604.598.5845  www.surrey.ca

**Comment by JackMc** [comment]
Progress update: Looks like the executable bit is indeed not set on Ubuntu 12.04 after a clean install. Looking into it.

**Comment by nknezevicsurrey** [comment]
Great.  I appreciate the update.

Cheers,

NENAD KNEZEVIC | GIS ANALYST

CITY OF SURREY
GIS Section
13450 104th Ave, Surrey, BC, Canada V3T 1V8
T 604.598.5845  www.surrey.ca

**Comment by JackMc** [comment]
This appears to be a bug in pip itself. The solution I have found is to install a newer version of pip like so:

```
$ pip install --upgrade pip
$ pip install --upgrade virtualenv
```

This solved the problem in my VM with the stock Python 2.7 - please tell me if it works for you

**Comment by JackMc** [comment]
Sorry, to amend to the previous: You should delete your virtualenv, and run the following commands outside of your virtualenv (run ``deactivate``):

```
$ sudo pip install --upgrade pip
$ sudo pip install --upgrade virtualenv
```

Then re-create your virtualenv. Finally, verify pip has been upgraded to the latest version:
```
$ pip --version
pip 7.1.0 from /usr/local/lib/python2.7/dist-packages
```

**Comment by nknezevicsurrey** [comment]
Just to clarify, do I still need to create a virtualenv before installing datacats or should the regular installation as per the documentation work after upgrading pip?

NENAD KNEZEVIC | GIS ANALYST

CITY OF SURREY
GIS Section
13450 104th Ave, Surrey, BC, Canada V3T 1V8
T 604.598.5845  www.surrey.ca

**Comment by JackMc** [comment]
Yes, I was assuming you were using a virtualenv, but if you upgrade pip, then install it like: ``pip install --no-cache-dir datacats`` it

**Comment by JackMc** [comment]
Did this end up working?

**Comment by nknezevicsurrey** [comment]
Hey,

Sorry I didn’t get a chance to try it yet.  Something else just fell on my plate so it might be a day or so until I get back to this.  I’ll let you know ASAP.

Thank you,

N

NENAD KNEZEVIC | GIS ANALYST

CITY OF SURREY
GIS Section
13450 104th Ave, Surrey, BC, Canada V3T 1V8
T 604.598.5845  www.surrey.ca

**Comment by JackMc** [comment]
That's ok, no rush

**Comment by nknezevicsurrey** [comment]
Now what happens is that when I reinstall datacats it brings in my previously created instance right away so I can’t recreate.  I’m guessing that –no-cache-dir is supposed to prevent this?

NENAD KNEZEVIC | GIS ANALYST

CITY OF SURREY
GIS Section
13450 104th Ave, Surrey, BC, Canada V3T 1V8
T 604.598.5845  www.surrey.ca

**Comment by JackMc** [comment]
I don't know if I'm understanding you correctly, but --no-cache-dir is so it doesn't install the same old version of Datacats (with the messed up execute bits)

**Comment by nknezevicsurrey** [comment]
Sorry never mind.  I don’t know what that was.  Or what I thought it was.

I got a different one now.

Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 53, in create
    datapusher=not opts['--no-datapusher'],
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 90, in create_environment
    fn()
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 315, in create_install_template_skin
    self.install_package_develop('ckanext-' + self.name + 'theme')
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 721, in install_package_develop
    stream_output=stream_output
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 736, in user_run_script
    stream_output=stream_output
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 769, in run_command
    commit=True, stream_output=stream_output)
  File "/usr/local/lib/python2.7/dist-packages/datacats/docker.py", line 183, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/run_as_user.sh /scripts/run.sh /project/ckanext-surreyckantheme
    Docker Error Log:
    useradd: UID 0 is not unique

NENAD KNEZEVIC | GIS ANALYST

CITY OF SURREY
GIS Section
13450 104th Ave, Surrey, BC, Canada V3T 1V8
T 604.598.5845  www.surrey.ca

**Comment by JackMc** [comment]
This seems to indicate that you're running Datacats as root - is that right?

**Comment by nknezevicsurrey** [comment]
I used sudo to install and when I tried to create the instance.  I would prefer not to run my CKAN instance as root.

However if I try to create the instance without sudo I get this:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 53, in create
    datapusher=not opts['--no-datapusher'],
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 61, in create_environment
    environment = Environment.new(environment_dir, '2.3', site_name, address=address, port=port)
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 115, in new
    name, datadir, srcdir = task.new_environment_check(path, site_name)
  File "/usr/local/lib/python2.7/dist-packages/datacats/task.py", line 284, in new_environment_check
    docker.require_images()
  File "/usr/local/lib/python2.7/dist-packages/datacats/docker.py", line 404, in require_images
    if (not image_exists('datacats/web') or
  File "/usr/local/lib/python2.7/dist-packages/datacats/docker.py", line 293, in image_exists
    return bool(_get_docker().images(name=name))
  File "/usr/local/lib/python2.7/dist-packages/datacats/docker.py", line 92, in _get_docker
    api_version = version_client.version()['ApiVersion']
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 815, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/clientbase.py", line 86, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
   resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))

NENAD KNEZEVIC | GIS ANALYST

CITY OF SURREY
GIS Section
13450 104th Ave, Surrey, BC, Canada V3T 1V8
T 604.598.5845  www.surrey.ca

**Comment by JackMc** [comment]
The issue here is probably that your user is not a member of the "docker" group. You may need to do something to the effect of this (where my non-root user is called jackmccracken):

```
usermod -aG docker jackmccracken
```

and then log in/out

**Comment by deniszgonjanin** [comment]
I think if you installed datacats with `sudo pip install`, that might be the issue. Do try installing it in a virtualenv if you can, that may just solve all the permission problems

**Comment by nknezevicsurrey** [comment]
I was just thinking that actually..

I’ll do a full reinstall.

Thanks,

NENAD KNEZEVIC | GIS ANALYST

CITY OF SURREY
GIS Section
13450 104th Ave, Surrey, BC, Canada V3T 1V8
T 604.598.5845  www.surrey.ca

**Comment by nknezevicsurrey** [comment]
OK that did it.  I must have installed datacats with sudo and that caused all this.

Now I still get this error when I try to create my instance.

Traceback (most recent call last):
  File "/home/gisadmin/ckan/ckan_env/local/lib/python2.7/site-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/home/gisadmin/ckan/ckan_env/local/lib/python2.7/site-packages/datacats/cli/create.py", line 53, in create
    datapusher=not opts['--no-datapusher'],
  File "/home/gisadmin/ckan/ckan_env/local/lib/python2.7/site-packages/datacats/cli/create.py", line 97, in create_environment
    log_syslog=log_syslog)
  File "/home/gisadmin/ckan/ckan_env/local/lib/python2.7/site-packages/datacats/cli/create.py", line 215, in finish_init
    environment.install_postgis_sql()
  File "/home/gisadmin/ckan/ckan_env/local/lib/python2.7/site-packages/datacats/environment.py", line 346, in install_postgis_sql
    links={self._get_container_name('postgres'): 'db'},
  File "/home/gisadmin/ckan/ckan_env/local/lib/python2.7/site-packages/datacats/docker.py", line 183, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/install_postgis.sh
    Docker Error Log:
    psql: FATAL:  could not open relation mapping file "global/pg_filenode.map": No such file or directory

NENAD KNEZEVIC | GIS ANALYST

CITY OF SURREY
GIS Section
13450 104th Ave, Surrey, BC, Canada V3T 1V8
T 604.598.5845  www.surrey.ca
