### ISSUE TITLE
datacats restart is broken

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#266]
* docker 1.7.1
* datacats latest master
* created new environment
* datacats reload works
* datacats stop, then start is broken:
```
(datacats)florianm@ip-172-31-14-85:/var/projects/datacats/catstown$ datacats stop
(datacats)florianm@ip-172-31-14-85:/var/projects/datacats/catstown$ datacats start
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats start

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/mnt/btrfsvol/projects/datacats/datacats/datacats/cli/main.py", line 100, in main
    return command_fn(environment, opts)
  File "/mnt/btrfsvol/projects/datacats/datacats/datacats/cli/manage.py", line 68, in start
    reload_(environment, opts)
  File "/mnt/btrfsvol/projects/datacats/datacats/datacats/cli/manage.py", line 96, in reload_
    if opts['PORT'] or opts['--address'] != '127.0.0.1' or opts['--site-url']:
KeyError: '--site-url'

----------------------------------------
```

retrying with --site-url explicitly given is also broken, with and without =
```
(datacats)florianm@ip-172-31-14-85:/var/projects/datacats/catstown$ datacats start --site-url http://catstown.yes-we-ckan.org
Usage:
  datacats start [-b] [-p|--no-watch] [-s NAME] [--syslog] [--address=IP] [ENVIRONMENT [PORT]]
  datacats start -r [-b] [-s NAME] [--syslog] [--address=IP] [ENVIRONMENT]
(datacats)florianm@ip-172-31-14-85:/var/projects/datacats/catstown$ datacats start --site-url=http://catstown.yes-we-ckan.org
Usage:
  datacats start [-b] [-p|--no-watch] [-s NAME] [--syslog] [--address=IP] [ENVIRONMENT [PORT]]
  datacats start -r [-b] [-s NAME] [--syslog] [--address=IP] [ENVIRONMENT]
```
cli/manage.py has some inconsistencies in specifying --site-url=URL (create) and --site-url URL (reload) - possible cause: is datacats start missing the --site-url?

however, datacats reload will start my environment! (phew)

**Comment by JackMc** [comment]
There's a fix for this up on master now

**Comment by JackMc** [comment]
Please report back on if it's fixed for you and close if yes :smile:

**Comment by florianm** [comment]
@JackMc it's fixed! datacats stop, then start stops and restarts the containers as expected. Thanks!
