### ISSUE TITLE
psql error when creating datacats instance

### ISSUE THREAD

**Issue by nknezevicsurrey** [datacats/datacats#267]
I have successfully installed datacats in a virtualenv on Ubuntu 12.04.  After pulling the images I try to create a datacats instance with the virtualenv still active.

When it gets to the initialize database step I get the error message below.

Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/home/gisadmin/ckan/venv/local/lib/python2.7/site-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/home/gisadmin/ckan/venv/local/lib/python2.7/site-packages/datacats/cli/create.py", line 53, in create
    datapusher=not opts['--no-datapusher'],
  File "/home/gisadmin/ckan/venv/local/lib/python2.7/site-packages/datacats/cli/create.py", line 97, in create_environment
    log_syslog=log_syslog)
  File "/home/gisadmin/ckan/venv/local/lib/python2.7/site-packages/datacats/cli/create.py", line 215, in finish_init
    environment.install_postgis_sql()
  File "/home/gisadmin/ckan/venv/local/lib/python2.7/site-packages/datacats/environment.py", line 346, in install_postgis_sql
    links={self._get_container_name('postgres'): 'db'},
  File "/home/gisadmin/ckan/venv/local/lib/python2.7/site-packages/datacats/docker.py", line 183, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/install_postgis.sh
    Docker Error Log:
    psql: FATAL:  could not open relation mapping file "global/pg_filenode.map": No such file or directory

Thanks,

N

**Comment by JackMc** [comment]
Are you init'ing from a previous datacats install or is this completely new? I cannot reproduce on my 12.04 VM

**Comment by nknezevicsurrey** [comment]
Hi, sorry for the late reply.

It’s a fresh install.  I’m installing in the virtualenv as instructed.  When I had to re-install I deleted the virtualenv as well as the .datacats folder.  Then I reinstalled.  Is there anything else I should clean up?

NENAD KNEZEVIC | GIS ANALYST

CITY OF SURREY
GIS Section
13450 104th Ave, Surrey, BC, Canada V3T 1V8
T 604.598.5845  www.surrey.ca

**Comment by nknezevicsurrey** [comment]
Any update on this?  Should I do anything else to clean up a previous install?

**Comment by JackMc** [comment]
Sorry for how long it took me! Try this command:

```
docker stop $(docker ps -a | grep "datacats" | tr -s ' ' | cut -f1 -d ' ')
docker rm $(docker ps -a | grep "datacats" | tr -s ' ' | cut -f1 -d ' ')
```

Then doing the removal from above once over

**Comment by nknezevicsurrey** [comment]
That did it.  THank you!
