### ISSUE TITLE
Error with older environments on datacats init

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#269]
When I do a 'purge' and an 'init' for any environment that's more than a few weeks old, this happens:

```
$ datacats init
Creating environment myckan/primary from existing environment directory "myckan"..
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats init

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/dz/source/datacats/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/Users/dz/source/datacats/datacats/cli/create.py", line 197, in init
    fn()
  File "/Users/dz/source/datacats/datacats/environment.py", line 227, in create_virtualenv
    self._preload_image(), self._get_container_name)
  File "/Users/dz/source/datacats/datacats/task.py", line 408, in create_virtualenv
    commit=True,
  File "/Users/dz/source/datacats/datacats/docker.py", line 167, in web_command
    entrypoint=entrypoint)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.2.2-py2.7.egg/docker/client.py", line 484, in create_container
    return self.create_container_from_config(config, name)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.2.2-py2.7.egg/docker/client.py", line 492, in create_container_from_config
    return self._result(res, True)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.2.2-py2.7.egg/docker/client.py", line 126, in _result
    self._raise_for_status(response)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.2.2-py2.7.egg/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 404 Client Error: Not Found ("No such image: datacats/ckan:2.3 (tag: 2.3)")

```

**Comment by JackMc** [comment]
This can be fixed (probably) by doing a ``datacats pull``

**Comment by JackMc** [comment]
Please close if it does :)

**Comment by deniszgonjanin** [comment]
Yes, all good
