### ISSUE TITLE
Error on new install, fresh machine

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#279]
Ubuntu 14.04 on Digital Ocean. After `pip install datacats` and `datacats pull`...

```
datacats create test
Creating environment "test/primary".....
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create test

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

-------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 53, in create
    datapusher=not opts['--no-datapusher'],
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 90, in create_environment
    fn()
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 283, in create_ckan_ini
    ro={RUN_AS_USER: '/scripts/run_as_user.sh'},
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 770, in run_command
    commit=True, stream_output=stream_output)
  File "/usr/local/lib/python2.7/dist-packages/datacats/docker.py", line 183, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/run_as_user.sh /usr/lib/ckan/bin/paster make-config ckan /project/development.ini
    Docker Error Log:
    useradd: UID 0 is not unique

----------------------------------------
```

**Comment by wardi** [comment]
datacats doesn't run as root at the moment

**Comment by deniszgonjanin** [comment]
Ok, maybe leave this open until the docs are updated
