### ISSUE TITLE
Postgres container is broken

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#287]
This seems to be an issue that affects any datacats version after doing a `datacats pull`, so it's likely that the Postgres image our own image depends on is broken.

```
$ datacats create test3
Creating environment "test3/primary"...........
Installing ckan
Installing ckanext-test3theme
Installing datapusher
Installing ckan requirements
Installing datapusher requirements
Initializing database
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create test3

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

---------------------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/home/datacats/datacats/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/home/datacats/datacats/datacats/cli/create.py", line 53, in create
    datapusher=not opts['--no-datapusher'],
  File "/home/datacats/datacats/datacats/cli/create.py", line 97, in create_environment
    log_syslog=log_syslog)
  File "/home/datacats/datacats/datacats/cli/create.py", line 215, in finish_init
    environment.install_postgis_sql()
  File "/home/datacats/datacats/datacats/environment.py", line 346, in install_postgis_sql
    links={self._get_container_name('postgres'): 'db'},
  File "/home/datacats/datacats/datacats/docker.py", line 172, in web_command
    volumes_from=volumes_from)
  File "/home/datacats/.virtualenvs/datacats/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 20, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/datacats/.virtualenvs/datacats/local/lib/python2.7/site-packages/docker/client.py", line 798, in start
    self._raise_for_status(res)
  File "/home/datacats/.virtualenvs/datacats/local/lib/python2.7/site-packages/docker/clientbase.py", line 104, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Cannot start container f93d2cd0e5be820bd8e5a65ba81d505ae76425587386a89c7d893a974128413e: Cannot link to a non running container: /datacats_postgres_test3_primary AS /dreamy_banach/db")

----------------------------------------
```

**Comment by deniszgonjanin** [comment]
This may be caused by this recently merged PR to the official Postgres Docker image: https://github.com/docker-library/postgres/pull/75

**Comment by deniszgonjanin** [comment]
Fixed with new images uploaded this morning by @JackMc
