### ISSUE TITLE
datacats create broken

### ISSUE THREAD

**Issue by cds-amal** [datacats/datacats#289]
# Environment
```
Mac OSX 10.10.4, 14GB RAM
datacats installed in virtualenv

(ckan)amal@hbox /Volumes/Sofai/python-projects/ckan $ which python                                                                                                                   
/Volumes/dev/python-projects/ckan/bin/python

(ckan)amal@hbox /Volumes/Sofai/python-projects/ckan $ python --version                                                                                                               
Python 2.7.6

(ckan)amal@hbox /Volumes/Sofai/python-projects/ckan $ datacats --version                                                                                                             
1.0.3

(ckan)amal@hbox /Volumes/Sofai/python-projects/ckan $ docker --version                                                                                                             
Docker version 1.7.1, build 786b29d

(ckan)amal@hbox /Volumes/Sofai/python-projects/ckan $ which datacats                                                                                                                 
/Volumes/Sofai/python-projects/ckan/bin/datacats

(ckan)amal@hbox /Volumes/Sofai/python-projects/ckan $ docker images                                                                                                                  
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
datacats/web        preload-2.3         c1a75215802d        18 hours ago        602.3 MB
datacats/web        latest              b266461fc468        18 hours ago        483.4 MB
datacats/postgres   latest              5f97eb4f2e8b        18 hours ago        459.7 MB
datacats/solr       latest              712bc510d411        18 hours ago        373.4 MB
datacats/web        preload-master      c7f7e470b955        3 weeks ago         601.8 MB
datacats/web        preload-2.4b        5711823dd122        3 weeks ago         601.4 MB
```
# Command
```
(ckan)amal@hbox /Volumes/Sofai/python-projects/ckan $ datacats create myckan
Creating environment "myckan/primary"....
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create myckan

It is seems to be a bug...<snip>
```

# Trace
```
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Volumes/Sofai/python-projects/ckan/lib/python2.7/site-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/Volumes/Sofai/python-projects/ckan/lib/python2.7/site-packages/datacats/cli/create.py", line 53, in create
    datapusher=not opts['--no-datapusher'],
  File "/Volumes/Sofai/python-projects/ckan/lib/python2.7/site-packages/datacats/cli/create.py", line 90, in create_environment
    fn()
  File "/Volumes/Sofai/python-projects/ckan/lib/python2.7/site-packages/datacats/cli/create.py", line 76, in <lambda>
    lambda: environment.create_source(datapusher),
  File "/Volumes/Sofai/python-projects/ckan/lib/python2.7/site-packages/datacats/environment.py", line 249, in create_source
    task.create_source(self.target, self._preload_image(), datapusher)
  File "/Volumes/Sofai/python-projects/ckan/lib/python2.7/site-packages/datacats/task.py", line 429, in create_source
    srcdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Volumes/Sofai/python-projects/ckan/myckan/ckan/ckan/config/who.ini'
```

**Comment by JackMc** [comment]
Hi there! We're looking into this now.

**Comment by cds-amal** [comment]
I removed the virtualenv variable by installing on the system python and the same error occurred.

**Comment by JackMc** [comment]
So I think we've figured this out:

Boot2docker unfortunately has a limitation where, outside of the /Users directory, volume mounts don't work. The vast majority of work (including hosting the site) in datacats is done through web container instances, so we need to mount things for pretty much any command to work. 

Our current suggestion would be to run your DataCats environments somewhere inside that directory (presumably your home directory). We will leave a reference to this issue in the Docker-machine support thread #98.

**Comment by cds-amal** [comment]
Thanks for the quick investigation @JackMc. My machine setup will make this inconvenient. boot volume is an SSD, and apps (include boot2docker) reside on another volume. Will investigate the VM/vagrant route.

**Comment by JackMc** [comment]
Yes, if you want to host it there, the best solution is a real Ubuntu VM running Docker.

What I usually do nowadays is have a Ubuntu server VM with shhd installed, and it works really nice.

**Comment by wardi** [comment]
Closing as there isn't much we can do without a fix for docker-machine/boot2docker
