### ISSUE TITLE
problems with datacats paster db load - postgresql-client-9.3 missing from datacats/web?

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#290]
I did a `paster db dump` on a non-datacats CKAN instance (which dumps the db to a .sql file), ran `datacats paster db clean` on a new datacats setup, then tried to `datacats paster db load` the sql file from the non-datacats CKAN, unfortunately running into

```
(datacats)florianm@aws-eco-001:/mnt/projects/datacats/internal$ datacats paster db load /mnt/ckan/private/dbdumps/2015-08-07/ckan_private.sql          
/bin/sh: 1: psql: not found
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/project/ckan/ckan/lib/cli.py", line 238, in command
    self.load()
  File "/project/ckan/ckan/lib/cli.py", line 315, in load
    pg_cmd = self._postgres_load(dump_path)
  File "/project/ckan/ckan/lib/cli.py", line 290, in _postgres_load
    self._run_cmd(pg_cmd)
  File "/project/ckan/ckan/lib/cli.py", line 297, in _run_cmd
    raise SystemError('Command exited with errorcode: %i' % retcode)
SystemError: Command exited with errorcode: 127
```

This sounds like postgresql-client-9.3 is missing from the datacats/web (or datacats/web:latest which I'm running).

**Comment by wardi** [comment]
I believe @deniszgonjanin fixed this with #322
