### ISSUE TITLE
error on "datacats create <name>"

### ISSUE THREAD

**Issue by reneenoble** [datacats/datacats#318]
When I run datacats create <name> I get this error 

datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create cos

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 54, in create
    site_url=opts['--site-url'],
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 91, in create_environment
    fn()
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 303, in create_ckan_ini
    ro={scripts.get_script_path('run_as_user.sh'): '/scripts/run_as_user.sh'},
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 833, in run_command
    commit=True, stream_output=stream_output)
  File "/usr/local/lib/python2.7/dist-packages/datacats/docker.py", line 183, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/run_as_user.sh /usr/lib/ckan/bin/paster make-config ckan /project/development.ini
    Docker Error Log:
    useradd: UID 0 is not unique

**Comment by JackMc** [comment]
Datacats doesn't support running as root.
