### ISSUE TITLE
datacats init leads to error when using docker toolbox

### ISSUE THREAD

**Issue by Mbrownshoes** [datacats/datacats#326]
I’m having some problems when it comes to run (on mac os)
./unroll.sh < .extensions

Running datacats init leads to 'boot2docker is not powered on. Please run "boot2docker up”.’ However, when I run 'boot2docker up’ I get a warning that the boot2docker command line intercase has been deprecated and I should use the Docker Toolbox, which I installed. We’re these instructions created for a previous version of docker? 

Before I installed boot2docker (which I did after doing some reading online - though those were probably written for an older version of docker..), I had received this error when I ran 'datacats init':

-----------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats init

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/datacats/cli/create.py", line 170, in init
    environment = Environment.load(environment_dir, site_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/datacats/environment.py", line 140, in load
    environment_name, data_only)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/datacats/task.py", line 130, in find_environment_dirs
    docker.require_images()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/datacats/docker.py", line 414, in require_images
    if (not image_exists('datacats/web') or
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/datacats/docker.py", line 297, in image_exists
    return bool(_get_docker().images(name=name))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/datacats/docker.py", line 92, in _get_docker
    api_version = version_client.version()['ApiVersion']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker/client.py", line 837, in version
    return self._result(self._get(url), json=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docker/clientbase.py", line 86, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: no appropriate commonName or subjectAltName fields were found

---------------------------------

**Comment by deniszgonjanin** [comment]
So, if you're using Docker Toolbox, I think you need to be on datacats master branch right now. If you installed datacats with `pip`, you will want to stick with boot2docker.

It looks like you have boot2docker and docker running fine, so you should be good for now (assuming you still have boot2docker) 

As an aside, you can always make sure docker is running properly by running a simple command within a simple docker image with `docker run busybox ls`

The SSL error above sounds like something we've seen before. Do you think you can try installing datacats inside a [virtualenv](https://virtualenv.pypa.io/en/latest/), and see if that fixes it? It should be as easy as:
```
pip install virtualenv
virtualenv ckan
source ckan/bin/activate
pip install datacats
```

Then try doing `datacats create`, which should create a simple stock CKAN 2.3 instance. If that works, then all should be set up properly.

**Comment by Mbrownshoes** [comment]
When I tried datacats create stuff I get 
boot2docker is not powered on. Please run "boot2docker up".
and then again when I run "boot2docker up", I get.

WARNING: The 'boot2docker' command line interface is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.

error in run: Failed to start machine "boot2docker-vm": exit status 1

So should I uninstall docker toolbox? I have tried and had no luck..

**Comment by deniszgonjanin** [comment]
Hmm. You could try downloading boot2docker again and doing a clean install. Alternatively if you prefer to stick with docker toolbox, you can clone datacats inside that virtualenv and do `python setup.py install` inside the datacats folder, which should give you a version of datacats that works with toolbox.

In either case, you just need a docker install that works. Beyond that things are easier :)

**Comment by wardi** [comment]
@Mbrownshoes has this resolved your issue?
