### ISSUE TITLE
Issue with most recent datacats pull -- create

### ISSUE THREAD

**Issue by byndcivilization** [datacats/datacats#329]
Im getting a funny error with a fresh install of datacats. 

```$ datacats create testing
Creating environment "testing/primary"../Library/Python/2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/utils/utils.py:458: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
..
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create testing

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/cli/create.py", line 57, in create
    site_url=opts['--site-url'],
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/cli/create.py", line 94, in create_environment
    fn()
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/cli/create.py", line 80, in <lambda>
    lambda: environment.create_source(datapusher),
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/environment.py", line 258, in create_source
    task.create_source(self.target, self._preload_image(), datapusher)
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/task.py", line 454, in create_source
    image=preload_image)
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/docker.py", line 208, in web_command
    logs = _get_docker().logs(c['Id'])
  File "/Library/Python/2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/utils/decorators.py", line 20, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/client.py", line 587, in logs
    return self._get_result(container, stream, res)
  File "/Library/Python/2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/clientbase.py", line 253, in _get_result
    cont = self.inspect_container(container)
  File "/Library/Python/2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/utils/decorators.py", line 20, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/client.py", line 511, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/Library/Python/2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/clientbase.py", line 87, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', ResponseNotReady())

----------------------------------------```

**Comment by byndcivilization** [comment]
A subsequent start call throws the following. 
    $ datacats start testing
    ----------------------------------------
    datacats: problem was encountered:
    Missing files in source directory:
    schema.xml
    development.ini
    who.ini
    ----------------------------------------

**Comment by byndcivilization** [comment]
This happens both locally and with an AWS provisioned instance

**Comment by JackMc** [comment]
I will look into this :-)

**Comment by byndcivilization** [comment]
Was there ever any solution to this?

**Comment by wardi** [comment]
@byndcivilization @JackMc was looking in to a new release of docker-py as the likely cause. If that's the case we'll pin the older version for now.

**Comment by byndcivilization** [comment]
I just found the error. I had an older version of requests installed. I found [this thread](https://github.com/locustio/locust/issues/273) pointing to onclosed connections. Either way requests 2.7 fixes this. Maybe force an pip update?

I'm getting a second error set though:

**Comment by byndcivilization** [comment]
$ datacats create test
Creating environment "test/primary"../Library/Python/2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/utils/utils.py:458: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
..
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create test

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/cli/create.py", line 57, in create
    site_url=opts['--site-url'],
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/cli/create.py", line 94, in create_environment
    fn()
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/cli/create.py", line 80, in <lambda>
    lambda: environment.create_source(datapusher),
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/environment.py", line 258, in create_source
    task.create_source(self.target, self._preload_image(), datapusher)
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/task.py", line 454, in create_source
    image=preload_image)
  File "/Users/cperry/Developer/cl-tools/datacats/datacats/docker.py", line 212, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /bin/cp -a /project/ckan /project_target/ckan
    Docker Error Log:
    /bin/cp: cannot create symbolic link '/project_target/ckan/contrib/docker/solr/schema.xml': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/doc/changelog.rst': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v05_block/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v06_super/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v10_custom_snippet/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/custom_config_setting/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v09_snippet/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v04_ckan_extends/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v14_more_custom_css/public/promoted-image.jpg': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v14_more_custom_css/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v14_more_custom_css/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v18_snippet_api/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v15_fanstatic/public/promoted-image.jpg': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v15_fanstatic/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v15_fanstatic/templates/home': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v21_custom_jquery_plugin/templates/ajax_snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v21_custom_jquery_plugin/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v21_custom_jquery_plugin/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/public/promoted-image.jpg': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/templates/home': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v12_extra_public_dir/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v12_extra_public_dir/templates/home/layout1.html': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v07_helper_function/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v17_popover/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v20_pubsub/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v20_pubsub/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v20_pubsub/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_02_error_handling/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_02_error_handling/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_02_error_handling/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_01_error/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_01_error/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_01_error/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v11_HTML_and_CSS/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v03_jinja/plugin.py': Protocol error

----------------------------------------

**Comment by wardi** [comment]
This looks like a problem with the way the source directory is mounted. Is this error on OSX or Linux?

**Comment by byndcivilization** [comment]
osx
docker-machine version 0.4.1
virtual box version 5.0.4r102546

**Comment by wardi** [comment]
@byndcivilization are you on OSX and trying to create an environment directory that isn't under /Users? The boot2docker VM seems to only be able to mount folders under /Users

**Comment by byndcivilization** [comment]
Ive tried on desktop, in my dev folder which is under home, in my home folder..

**Comment by byndcivilization** [comment]
Just to clarify this is happening after my move to docker-toolbox / docker-machine

**Comment by byndcivilization** [comment]
I had bother dockertool box and virtual box installed casks. I deleted both and reinstalled strictly from the docker toolbox img and the permission error persists. Is this an issue with the latest docker toolbox distrubtion?

**Comment by byndcivilization** [comment]
Doest work from fresh datacats install from master branch in virtualenv either.

**Comment by JackMc** [comment]
Looking into this.

**Comment by JackMc** [comment]
Can you try this on your Mac in your venv?

```
pip freeze | grep docker-py
```

**Comment by byndcivilization** [comment]
both in and out of venv its docker-py==1.4.0

**Comment by JackMc** [comment]
Thanks.

We believe there may have been a breaking change between docker-py 1.3.2 and 1.4.0. I’m looking into it now.

**Comment by byndcivilization** [comment]
awesome thanks and sorry blast you guys with messages

**Comment by JackMc** [comment]
That's ok! :-) We're always playing catch-up with the Docker peeps.

**Comment by JackMc** [comment]
I think I may have been wrong with that as the cause... it seems to be working fine on my machine.

May I ask if you're running on datacats master or the latest release?

**Comment by byndcivilization** [comment]
Yeah I just made the transition to toolbox and its been painful across the board.

**Comment by deniszgonjanin** [comment]
yea, it's been painful. I had to reinstall a couple of times. The toolbox install tries to migrate the boot2docker VM, but it doesn't do a great job

**Comment by byndcivilization** [comment]
Yes I'm on master I can try again to check if there's been a change

**Comment by JackMc** [comment]
Another question: Are you using a migrated boot2docker VM or a docker-machine VM?

**Comment by byndcivilization** [comment]
Fresh

**Comment by byndcivilization** [comment]
$ pip freeze | grep datacats
-e git+git@github.com:datacats/datacats.git@8acc18032642b096bbb3851075a0d4c1af17b5dc#egg=datacats-master
(ckan)

**Comment by byndcivilization** [comment]
$ datacats create test
Creating environment "test/primary"../Users/cperry/ckan/lib/python2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/utils/utils.py:458: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
..
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create test

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/cperry/datacats/datacats/cli/main.py", line 93, in main
    return command_fn(opts)
  File "/Users/cperry/datacats/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/Users/cperry/datacats/datacats/cli/create.py", line 104, in create_environment
    fn()
  File "/Users/cperry/datacats/datacats/cli/create.py", line 90, in <lambda>
    lambda: environment.create_source(datapusher),
  File "/Users/cperry/datacats/datacats/environment.py", line 259, in create_source
    task.create_source(self.target, self._preload_image(), datapusher)
  File "/Users/cperry/datacats/datacats/task.py", line 454, in create_source
    image=preload_image)
  File "/Users/cperry/datacats/datacats/docker.py", line 212, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /bin/cp -a /project/ckan /project_target/ckan
    Docker Error Log:
    /bin/cp: cannot create symbolic link '/project_target/ckan/doc/changelog.rst': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v07_helper_function/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/templates/home': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/public/promoted-image.jpg': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v17_popover/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v09_snippet/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v18_snippet_api/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v03_jinja/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v11_HTML_and_CSS/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v21_custom_jquery_plugin/templates/ajax_snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v21_custom_jquery_plugin/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v21_custom_jquery_plugin/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v10_custom_snippet/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v14_more_custom_css/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v14_more_custom_css/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v14_more_custom_css/public/promoted-image.jpg': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v04_ckan_extends/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_01_error/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_01_error/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_01_error/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v05_block/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v15_fanstatic/templates/home': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v15_fanstatic/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v15_fanstatic/public/promoted-image.jpg': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v20_pubsub/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v20_pubsub/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v20_pubsub/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/custom_config_setting/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_02_error_handling/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_02_error_handling/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_02_error_handling/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v12_extra_public_dir/templates/home/layout1.html': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v12_extra_public_dir/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v06_super/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/contrib/docker/solr/schema.xml': Protocol error

----------------------------------------
(ckan)

**Comment by JackMc** [comment]
So just as a confirmation:
* First, you installed boot2docker and had the tool working
* Second, you installed docker-machine and fixed a requests version, now it doesn't?

**Comment by byndcivilization** [comment]
Yes.
* Was running things on boot2docker
* Made the transition to docker-machine and things were still working but I ended up breaking some critical AWS stuff in the process so I did a fresh OSX install
* after fresh install I cant get datacats to work
    * tried cask installs of both VBox and Docker tools
    * tried dmg/img installs of both
    * for all of this I tried pip and master branch installs of Datacats

One thought, is there a way to run Datacats as root?

**Comment by JackMc** [comment]
Running Datacats as root is something we don't support because it causes problems with our images

**Comment by byndcivilization** [comment]
yeah that makes sense. So do you have any other suggestions?

**Comment by florianm** [comment]
FYI I'm running into the same error (docker_py==1.4.0)
```
(ckan)ubuntu@ip-172-31-22-195:/var/projects/ckan$ datacats create --ckan latest --site-url http://boom.alpha.data.wa.gov.au boom 5008
Creating environment "boom/primary"../mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/utils/utils.py:458: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
```

I'm running a Ubuntu VM with latest docker and datacats, run datacats commands as a non-root user, and I have symlinked datacats' data folder `~/.datacats` to a different location (wasn't a problem until today when I ran into #334).

**Comment by byndcivilization** [comment]
Is there any fix for this? Do I need to roll back to a previous dockery_py version?

**Comment by wardi** [comment]
There are a couple issues here, the one in https://github.com/datacats/datacats/issues/329#issuecomment-142301551 can be worked around with https://github.com/datacats/datacats/issues/340 is that the issue you're asking about?

If the original issue is resolved let's close this one and discuss on #340

**Comment by byndcivilization** [comment]
I'm still getting this with the most recent master branch and the most recent pull.

**Comment by byndcivilization** [comment]
Yes #340 .

**Comment by wardi** [comment]
for the error reported at the top, is the fix to require at least a specific version of requests?

**Comment by byndcivilization** [comment]
Yes. most recent version of requests works. 2.6 does not. I know this because 2.6 is required for aws cli tools.

**Comment by medined** [comment]
I am also running into this issue. My error message is 

```
./usr/local/lib/python2.7/site-packages/docker/utils/utils.py:629: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
```

In order to control the environment, I am using a Docker container to execute datacats. This is my Docker Run command:

```
docker run \
  --rm \
  -it \
  -v /usr/bin:/usr/bin:rw \
  -v $(pwd):/projects:rw \
  --workdir /projects \
  -v /var/run/docker.sock:/var/run/docker.sock \
  python:2.7 \
  /bin/bash
```

After the container starts, I run these commands:

```
pip install datacats
datacats pull
datacats create catstown
```

The error is displayed when the `datacats create` command is executed.

The following python packages were installed:

```
Successfully installed PyYAML-3.12 argh-0.26.2 args-0.1.0 backports.ssl-match-hostname-3.5.0.1 clint-0.5.1 datacats-1.2.0 docker-py-1.9.0 docopt-0.6.2 ipaddress-1.0.16 lockfile-0.12.2 pathtools-0.1.2 requests-2.11.1 six-1.10.0 watchdog-0.8.3 websocket-client-0.37.0
```
