### ISSUE TITLE
Running celery deamon

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#34]
Putting this here before putting in the docs, as it depends on https://github.com/ckan/ckan/pull/2326

You can run the celery deamon in a separate container now with

```
datacats shell . paster --plugin=ckan celeryd
```

Any extension can then push tasks to that daemon in normal celery fashion. 

What we will need is a way to run this container in the background, and also a way to run it in production

**Comment by florianm** [comment]
ckan/ckan#2326 seems to be merged!
There's a cyclic dependency requiring to start celeryd before ckanext-qa is installed. I'll write up working steps when I have them.

Could you add a container for celeryd, or should it be run via supervisor?

**Comment by deniszgonjanin** [comment]
Anything that runs with paster can be ran in a separate container of type `web`. And if you run it with `-d`, it will run in the background. For example:
```
datacats paster -d celeryd....
```

I run my harvesters like this, which need a full 3 extra containers...

**Comment by JackMc** [comment]
Remind me, what decision did we make re: celeryd?

**Comment by deniszgonjanin** [comment]
I don't think we made any decisions - which reminds me that I need to test that it actually works. I've only tested the harvesters with the new redis container

**Comment by florianm** [comment]
@deniszgonjanin did your celeryd run into a cyclic dependency with ckanext-qa?
And if you don't mind me asking, could you provide a working example of harvesting?
Did you run one `datacats paster -d celeryd` for each of gather, fetch and run? Or did you use the front-end at /harvest (with what config?)

Ideally I'd want to spin up two datacats environments, and run a ckan_harvester to harvest one into the other. My ckan harvest following the ckanext-harvest docs seems to time out (not sure whether it's my config, or I need the three celery containers). I could imagine a write-up of a working example would be immensely useful for the datacats docs :-)

**Comment by deniszgonjanin** [comment]
@florianm sure, I'll put out an example.

In the meantime -for harvester, I run one container for gather, one for fetch - and those two stay running. I run them with `datacats paster -d harvester gather_consumer` and `datacats paster -d harvester fetch_consumer`. For the run stage I still have a cron job on my host that runs `datacats paster harvester run` once a day. That part (periodic commands) is still manual, there's nothing in datacats that helps at the moment.

I'll try to get an example working for ckanext-qa as well, and publish those two as example datacats environments.

**Comment by florianm** [comment]
@deniszgonjanin thanks so much, that will help me further! So now it's only the harvester config left to fine-tune. FYI I'm writing up my working examples [here](http://govhack2015.readthedocs.org/en/latest/2_CKAN_extensions/) I'm happy to contribute upstream if you see fit and once it all works.

Last one, can you trigger the "run" stage from the /harvest GUI, and does the configured harvester show up there at all? Is your example a ckan_harvester or a custom one?

**Comment by deniszgonjanin** [comment]
@florianm I have an example here: https://github.com/deniszgonjanin/harvest

Try that out and see if it works for you. I'll try to do a similar one for qa using the built-in CKAN celery

**Comment by florianm** [comment]
@deniszgonjanin thanks, that got me further. The redis/celery side seems to work following your instructions, although I'm now in ckanext-scheming's bad books (off topic for this issue):

```Invalid package with GUID beeliar-wetlands-records: {'extras': [{'key': ['There is a schema field with the same name']}, {'key': ['There is a schema field with the same name']}]}
```
I'm using the same custom dataset schema in both the harvested and the harvesting CKAN. 

Re ckanext-qa, I'm still stuck:
```
(datacats)me@IP:/var/projects/datacats/catstown/ckanext-qa$ datacats paster -d celeryd
45dc1391dcdd5ce1aa7039dad2e97167ba606d4e88d268190557f7fb918a7a60
# this container doesn't seem to be running, probably crashes right away

(datacats)me@IP:/var/projects/datacats/catstown/ckanext-qa$ datacats paster qa update
2015-07-27 05:41:45,050 DEBUG [ckanext.scheming.plugins] Schema URL is ckanext.scheming:presets.json
2015-07-27 05:41:45,050 DEBUG [ckanext.scheming.plugins] Schema URL is ckanext.scheming:dpaw_dataset.json
2015-07-27 05:41:45,255 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-07-27 05:41:45,264 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-07-27 05:41:45,276 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-07-27 05:41:45,277 DEBUG [ckanext.harvest.model] Harvest tables already exist
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/project/ckanext-qa/ckanext/qa/commands.py", line 61, in command
    import tasks
  File "/project/ckanext-qa/ckanext/qa/tasks.py", line 11, in <module>
    from ckanext.archiver.tasks import link_checker, LinkCheckerError
ImportError: No module named archiver.tasks
```
I probably need some help getting the required celeryd container running, then I assume `datacats paster qa update/clean` would work.

**Comment by florianm** [comment]
Update on my key conflict:

* Harvested CKAN runs vanilla ckanext-spatial, with manually added extra "spatial" for GeoJSON geometry of spatial extent
* Harvesting CKAN runs my ckanext-spatial and ckanext-scheming with custom dataset schema, including field "spatial" for spatial extent

I got CKAN harvesting to work with two other datacats-based CKANs running with the same custom ckanext-scheming-defined dataset schema following instructions above. @deniszgonjanin thanks for the help, very appreciated!

**Comment by deniszgonjanin** [comment]
@florianm you're welcome! I'll try to put out a celery example soon as well

**Comment by JackMc** [comment]
Celery seems to work beautifully with the patch from https://github.com/ckan/ckan/pull/2548

**Comment by florianm** [comment]
if this fixes the "archiver.tasks not found" circular dependency on "qa update" my beers-owed-to-jack count increments to 4. need to start a tab for @deniszgonjanin too. cheers guys!
