### ISSUE TITLE
symlink error on macbook air

### ISSUE THREAD

**Issue by perceptron-XYZ** [datacats/datacats#340]
When I ran datacats create NEWENVIRONMENT on my macbook air, I got a string of symlink errors:

Traceback (most recent call last):
  File "/Users/RYAN/Documents/datacats/datacats/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/Users/RYAN/Documents/datacats/datacats/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/Users/RYAN/Documents/datacats/datacats/datacats/cli/create.py", line 104, in create_environment
    fn()
  File "/Users/RYAN/Documents/datacats/datacats/datacats/cli/create.py", line 90, in <lambda>
    lambda: environment.create_source(datapusher),
  File "/Users/RYAN/Documents/datacats/datacats/datacats/environment.py", line 259, in create_source
    task.create_source(self.target, self._preload_image(), datapusher)
  File "/Users/RYAN/Documents/datacats/datacats/datacats/task.py", line 454, in create_source
    image=preload_image)
  File "/Users/RYAN/Documents/datacats/datacats/datacats/docker.py", line 212, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /bin/cp -a /project/ckan /project_target/ckan
    Docker Error Log:
    /bin/cp: cannot create symbolic link '/project_target/ckan/contrib/docker/solr/schema.xml': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/doc/changelog.rst': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v20_pubsub/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v20_pubsub/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v20_pubsub/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v21_custom_jquery_plugin/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v21_custom_jquery_plugin/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v21_custom_jquery_plugin/templates/ajax_snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v09_snippet/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v10_custom_snippet/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v06_super/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/custom_config_setting/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v18_snippet_api/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v05_block/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v04_ckan_extends/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v15_fanstatic/public/promoted-image.jpg': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v15_fanstatic/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v15_fanstatic/templates/home': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v17_popover/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v07_helper_function/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v03_jinja/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v14_more_custom_css/public/promoted-image.jpg': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v14_more_custom_css/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v14_more_custom_css/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_01_error/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_01_error/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_01_error/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_02_error_handling/fanstatic/example_theme_popover.css': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_02_error_handling/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v19_02_error_handling/templates': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/public/promoted-image.jpg': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v13_custom_css/templates/home': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v11_HTML_and_CSS/plugin.py': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v12_extra_public_dir/templates/snippets': Protocol error
/bin/cp: cannot create symbolic link '/project_target/ckan/ckanext/example_theme/v12_extra_public_dir/templates/home/layout1.html': Protocol error

I tested the symlink functionality locally and also on VM, and both succeeded, so no idea what is exactly the reason for the error.
Currently, we worked around the symlink issue by replacing the command option '-a' of line 452 and 457 of task.py with  '-L -r'.

**Comment by byndcivilization** [comment]
I'm getting this issue also.

**Comment by wardi** [comment]
@byndcivilization can you try the workaround @perceptron-XYZ mentions?

@JackMc this would be a great thing to get fixed, would you try and find out why it seems we can't copy symlinks from the preloaded ckan image ...on certain machines... but we can create them just fine from a shell on all machines?

**Comment by JackMc** [comment]
So when we tried this out on Ryan's machine we couldn't create the files from the docker machine SSH prompt. Is that still the case?

**Comment by wardi** [comment]
@JackMc IIRC when he and I tried it creating symlinks from the ssh prompt seemed to work fine..

**Comment by byndcivilization** [comment]
got this message:

----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create test

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/cperry/datacats/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/Users/cperry/datacats/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/Users/cperry/datacats/datacats/cli/create.py", line 104, in create_environment
    fn()
  File "/Users/cperry/datacats/datacats/cli/create.py", line 97, in <lambda>
    lambda: environment.update_ckan_ini(skin=create_skin),
  File "/Users/cperry/datacats/datacats/environment.py", line 329, in update_ckan_ini
    self.run_command(command=command, rw_project=True)
  File "/Users/cperry/datacats/datacats/environment.py", line 853, in run_command
    commit=True, stream_output=stream_output)
  File "/Users/cperry/datacats/datacats/docker.py", line 212, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /usr/lib/ckan/bin/paster --plugin=ckan config-tool /project/development.ini -e sqlalchemy.url = postgresql://<hidden> ckan.datastore.read_url = postgresql://<hidden> ckan.datastore.write_url = postgresql://<hidden> ckan.datapusher.url = http://datapusher:8800 solr_url = http://solr:8080/solr ckan.storage_path = /var/www/storage ckan.plugins = datastore resource_proxy text_view datapusher recline_grid_view recline_graph_view test_theme ckan.site_title = test ckan.site_logo = ckan.auth.create_user_via_web = false
    Docker Error Log:
    Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 103, in run
    command = commands[command_name].load()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/project/ckan/ckan/lib/cli.py", line 12, in <module>
    import ckan.logic as logic
  File "/project/ckan/ckan/logic/__init__.py", line 8, in <module>
    import ckan.model as model
  File "/project/ckan/ckan/model/__init__.py", line 7, in <module>
    import vdm.sqlalchemy
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/vdm/sqlalchemy/__init__.py", line 31, in <module>
    from base import *
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/vdm/sqlalchemy/base.py", line 7, in <module>
    from sqlalchemy import *
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/__init__.py", line 52, in <module>
    from sqlalchemy.types import (
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/types.py", line 27, in <module>
    from sqlalchemy import exc, schema
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/schema.py", line 33, in <module>
    from sqlalchemy import event, events
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/event/__init__.py", line 7, in <module>
    from .api import CANCEL, NO_RETVAL, listen, listens_for, remove, contains
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/event/api.py", line 13, in <module>
    from .base import _registrars
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/event/base.py", line 42, in <module>
    class _Dispatch(object):
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/event/base.py", line 104, in _Dispatch
    @util.hybridmethod
AttributeError: 'module' object has no attribute 'hybridmethod'

**Comment by wardi** [comment]
@byndcivilization that's not the symlink error you were reporting before, so the workaround got you past that, rigth? This looks like the wrong version of sqlalchemy. would you make sure you have the latest images with `datacats pull`?

**Comment by byndcivilization** [comment]
yeah give me a about 30 minutes to redo everything

**Comment by byndcivilization** [comment]
Okay reinstalled all components and tried workaround with most recent pull and master branch. 

Got this error:
cperry at Laptop in ~
$ datacats create test
Creating environment "test/primary"../Library/Python/2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/utils/utils.py:458: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
.........

----------------------------------------
datacats: problem was encountered:
Couldn't connect to PyPi. Is your DNS configured correctly?

If you're using boot2docker, try restarting the VM:
boot2docker down
boot2docker up

----------------------------------------

**Comment by byndcivilization** [comment]
solr and postgres are working so getting closer

**Comment by deniszgonjanin** [comment]
I've seen this. Try `docker exec` into one of the containers, or `datacats shell`, and then ping google to check your docker containers have outside network access.

This usually happens to me when I change wifi networks, and my virtualbox choking up on networking. Restarting the VM works

**Comment by byndcivilization** [comment]
Halfway working. The VM DNS failure only happens on initialization. Ive restarted both the docker-machine image my full system and the same thing happens. "datacats create test" gives me the PyPi error. After that if i type "datacats start test" I get:
```
----------------------------------------
datacats: problem was encountered:
Error while starting web container:

----------------------------------------
```

However all the containers are running at this point. If i shell in to the web container and ping a website, it connects as expected. If i go to vbox url + port  get
```
503 Service Unavailable

The server is currently unavailable. Please try again at a later time.

This site is currently off-line. Database is not initialised.
```

**Comment by JackMc** [comment]
Could you try doing ``docker logs datacats_postgres_test_primary`` and ``docker logs datacats_web_test_primary`` and post the output here?

**Comment by byndcivilization** [comment]
```
$ docker logs datacats_postgres_test_primary
LOG:  database system was shut down at 2015-10-13 17:58:50 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  relation "user" does not exist at character 465
STATEMENT:  SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".openid AS user_openid, "user".fullname AS user_fullname, "user".email AS user_email, "user".apikey AS user_apikey, "user".created AS user_created, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".activity_streams_email_notifications AS user_activity_streams_email_notifications, "user".sysadmin AS user_sysadmin, "user".state AS user_state
	FROM "user"
	WHERE "user".name = 'default' OR "user".openid = 'default' OR "user".id = 'default' ORDER BY "user".name
	 LIMIT 1
ERROR:  relation "user" does not exist at character 465
STATEMENT:  SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".openid AS user_openid, "user".fullname AS user_fullname, "user".email AS user_email, "user".apikey AS user_apikey, "user".created AS user_created, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".activity_streams_email_notifications AS user_activity_streams_email_notifications, "user".sysadmin AS user_sysadmin, "user".state AS user_state
	FROM "user"
	WHERE "user".name = 'default' OR "user".openid = 'default' OR "user".id = 'default' ORDER BY "user".name
	 LIMIT 1
ERROR:  relation "system_info" does not exist at character 175
STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.revision_id AS system_info_revision_id
	FROM system_info
	WHERE system_info.key = 'ckan.config_update'
	 LIMIT 1
ERROR:  relation "system_info" does not exist at character 175
STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.revision_id AS system_info_revision_id
	FROM system_info
	WHERE system_info.key = 'ckan.config_update'
	 LIMIT 1
```

**Comment by byndcivilization** [comment]
```docker logs datacats_web_test_primary```
gives nothing

**Comment by JackMc** [comment]
This looks like the database initialization isn't working properly. My next suggested step would be to do a ``datacats reset test``. See if this fixes up your database.

**Comment by byndcivilization** [comment]
that worked but it looks like that needs to happen every time a user initialises a new CKAN site.

**Comment by JackMc** [comment]
That was more of a debugging suggestion than a actual solution. But I'm glad it works for you now. It's interesting that it works now. Does the database initialization step in create mess up for you?

**Comment by byndcivilization** [comment]
Yes, everytime i create a new environment.

**Comment by byndcivilization** [comment]
I wonder, is there any datacats create option that links to a non-docker psql instance. When OKF were playing with this they had a link option that allowed passing psql uri and authentication env vars.

**Comment by deniszgonjanin** [comment]
@byndcivilization not at the moment - one of the key goals of datacats was to achieve maximum development/production parity; i.e. a fully self-contained CKAN instance, that works in production exactly as it does in development.
