### ISSUE TITLE
Docker APIError 500: no space left on device

### ISSUE THREAD

**Issue by florianm** [datacats/datacats#344]
datacats ckan --latest runs at `datacats install` into:
```
(ckan)ubuntu@ip-172-31-18-211:/mnt/btrfsvol/projects/ckan/datawagovau$ datacats install --clean
/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/utils/utils.py:458: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
Cleaning environment datawagovau of pyc files...
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats install --clean

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/mnt/btrfsvol/projects/ckan/datacats/datacats/cli/main.py", line 99, in main
    return command_fn(environment, opts)
  File "/mnt/btrfsvol/projects/ckan/datacats/datacats/cli/install.py", line 35, in install
    install_all(environment, opts['--clean'], verbose=not opts['--quiet'])
  File "/mnt/btrfsvol/projects/ckan/datacats/datacats/cli/install.py", line 91, in install_all
    environment.install_extra()
  File "/mnt/btrfsvol/projects/ckan/datacats/datacats/environment.py", line 251, in install_extra
    rw_venv=True
  File "/mnt/btrfsvol/projects/ckan/datacats/datacats/environment.py", line 819, in user_run_script
    stream_output=stream_output
  File "/mnt/btrfsvol/projects/ckan/datacats/datacats/environment.py", line 852, in run_command
    commit=True, stream_output=stream_output)
  File "/mnt/btrfsvol/projects/ckan/datacats/datacats/docker.py", line 214, in web_command
    rval = _get_docker().commit(c['Id'])
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/utils/decorators.py", line 20, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/client.py", line 193, in commit
    json=True)
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/clientbase.py", line 119, in _result
    self._raise_for_status(response)
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/clientbase.py", line 115, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("mktemp failed: mkdir /mnt/btrfsvol/docker/graph/_tmp/5ec0b0ae882dbfdf2d29777a137934aa07d1f3f3727022b7f73f1d5f1a5a3e15: no space left on device")
```

* I'm not out of hd space (80 GB available)
* I've got enough inodes (1% in use)
* I have run https://github.com/chadoe/docker-cleanup-volumes
* I still have a metric ton of docker images (1077, most named <none>)

Short of `docker rmi $(docker images -q)`, how do I clean out my datacats images after four months of vigorous datacatting?

**Comment by florianm** [comment]
Fun fact: `docker rmi $(docker images -q)` only nukes the images of non-running containers. I kept the few non-datacats containers I need up and running, and `docker rmi` left me 20-odd relevant of the 1077 images. Good job, `docker rmi`.

**Comment by deniszgonjanin** [comment]
Yes, we should document this in the FAQ. I'll mark this as a docs bug, I don't know that we can do much else about it

**Comment by florianm** [comment]
This happened after three months of trial and error, building images
locally and general abuse. The how to remove docker images instructions
might be a good fit in the development section?

**Comment by florianm** [comment]
Problem is solved, solution above and in PR to docs.
