### ISSUE TITLE
Paster command cannot write to .ini file

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#347]
Creating a new ckan extension using the CKAN paster command fails because the .ini is not writeable by the container. It's not an often used command, but documenting here anyway for reference:

`$ paster create -t ckanext ckanext-test`
```
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/create_distro.py", line 191, in command
    self.write_vars(self.options.config, write_vars)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 760, in write_vars
    p.write(open(config, 'w'))
IOError: [Errno 30] Read-only file system: '/project/development.ini'
```

**Comment by deniszgonjanin** [comment]
Easy way to get around this is to do it in the shell:

```
$ datacats shell
$ paster create -t ckanext ckanext-test
```

I'm marking this as a docs bug, given the infrequency of use of this command a docs update is sufficient.

**Comment by JackMc** [comment]
The issue here is that the development.ini inside that container is basically temp, as it's the auto generated one.

**Comment by JackMc** [comment]
So that fix will only be temporary till the user manually adds the extension to the development.ini in the actual source dir

**Comment by deniszgonjanin** [comment]
That's still fine, most of what the command does is setup a skeleton project, and those files do stick around. People can add the new extension to the .ini manually

**Comment by wardi** [comment]
strange. datacats paster should be calling environment.interactive_shell. the permissions on that file should be the same.

**Comment by deniszgonjanin** [comment]
yes, the changes to that file do not persist with either `datacats shell` or `datacats paster`. What we want is for the ckanext skeleton project to persist, which it does with `datacats shell` and not with `datacats paster`

**Comment by wardi** [comment]
did it get created under the ckan directory instead? IIRC datacats paster switches into the directory of the extension (in this case ckan) before running commands, because it's harder to figure out what the `--plugin` option should be

**Comment by deniszgonjanin** [comment]
No, I think everything works fine with `datacats shell` except that after you shut down the container, the changes to development.ini are reverted. I'm not sure, give it a try
