### ISSUE TITLE
Issue creating datacats environment in AWS environment using docker-machine

### ISSUE THREAD

**Issue by byndcivilization** [datacats/datacats#349]
Latest pull using master branch
```
$ datacats create newawstest
Creating environment "newawstest/primary"../Library/Python/2.7/site-packages/docker_py-1.4.0-py2.7.egg/docker/utils/utils.py:458: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
..
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create newawstest

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/cperry/datacats/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/Users/cperry/datacats/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/Users/cperry/datacats/datacats/cli/create.py", line 104, in create_environment
    fn()
  File "/Users/cperry/datacats/datacats/cli/create.py", line 90, in <lambda>
    lambda: environment.create_source(datapusher),
  File "/Users/cperry/datacats/datacats/environment.py", line 258, in create_source
    task.create_source(self.target, self._preload_image(), datapusher)
  File "/Users/cperry/datacats/datacats/task.py", line 462, in create_source
    srcdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/cperry/newawstest/ckan/ckan/config/who.ini'

----------------------------------------
```

**Comment by byndcivilization** [comment]
This is a vanilla ec2 instance created with docker-machine:
```
docker-machine -D create --driver amazonec2 --amazonec2-access-key $AWS_ACCESS_KEY_ID --amazonec2-secret-key $AWS_SECRET_ACCESS_KEY --amazonec2-vpc-id $AWS_VPC_ID --amazonec2-zone a test-datacats
```

**Comment by byndcivilization** [comment]
Images pullled to docker agent but no containers were created.

**Comment by wardi** [comment]
Seems like volume mounts aren't working in your docker machine VM. This could be by design, I'm not sure. Deploying with docker machine isn't something we've worked on yet, we're still working out the last few issues with using it locally.

**Comment by byndcivilization** [comment]
okay is there any production deployment strategy yet or will this come after dealing with local issues?

**Comment by wardi** [comment]
datacats is tested on Debian/Ubuntu VMs and bare metal. Deployment is just rsyncing the environment source directory and running `datacats install` or `reload`

**Comment by deniszgonjanin** [comment]
@byndcivilization right now our strategy for custom deployment is pretty much that. Switching to docker-machine has been a bit tricky, but it's really the majority of the work needed to make datacats work with remote docker-machines. Once the local issues are sorted out, automating the rsync/install/reload process somehow is the big remaining piece.

**Comment by byndcivilization** [comment]
yeah totally understand. Docker-machine seems nice in the long run but is killing me in the short.

So I'm trying to think through how this would work in AWS. Current docker options are ECS, docker-machine, elasticbeanstalk and creating a docker agent from scratch on a fresh EC2 instance. It seams like the current iteration of Datacats is point towards the last option. Am I missing something or is that correct? 

I actually have a side question on backups/disaster recovery and persistent data. It seems like the current implementation of datacats is storing data volumes on my host instead of the remote host for remote deployments (which seems to be whats happening above, right?). The plan is store this on remote host, correct? Just want to make sure I'm not missing something. I currently am running some other web services on ECS with data volumes stored on attached EBS and have the EBS volumes tagged for automatic back up via cron job. This was a headache to think through 

I had actually tried to create a DIY version of datacats right before you guys launched and had it linked up to a persistent postgres RDS instance. That seemed to work well but got I got stuck dealing with the solr container and how to reindex when moving hosts. Is it possible in the current implementation to link to an external db?

**Comment by deniszgonjanin** [comment]
Right now when using datacats, the way to go would be a fresh EC2 instance. To make deployment easy, we version-control our datacats environments, clone them on a fresh server, and spin up the environment with datacats. 

For backups, right now datacats still assumes you are interacting with a local CKAN instance, which is why the volumes are always mounted locally. In fact all docker-machine problems you encounter as probably directly related to this assumption. Once remote docker-machine is supported, datacats should recognize that and not try to mount volumes locally.

You should be able to use the same approach you mention above for your backups - there is no special magic in datacats containers, so they can be stored on EBS and backed up periodically with cron. Alternatively, if you want to backup a sql dump instead of filesystem blobs, a cron job that runs pg_dump on the database also works and is a bit easier to restore when needed.

**Comment by byndcivilization** [comment]
Hi all. Sorry to reopen this but is there plans to incorporate any of the advantages of docker-machine in the near future?

**Comment by wardi** [comment]
IIUC we can export a datacats environment to docker compose then it should be possible to use docker machine. I don't know when that will be worked on.
