### ISSUE TITLE
os x connectionerror on datacats open

### ISSUE THREAD

**Issue by husker** [datacats/datacats#359]
I had ckan up and running on osx using datacats until i rebooted my machine. now i'm unable to launch ckan:

(venv)Jamess-MacBook-Air:bcgov james$ datacats open
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats open

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/cli/main.py", line 96, in main
    opts['--site'] if '--site' in opts else 'primary')
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/environment.py", line 141, in load
    environment_name, data_only)
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/task.py", line 130, in find_environment_dirs
    docker.require_images()
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/docker.py", line 420, in require_images
    if (not image_exists('datacats/web') or
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/docker.py", line 303, in image_exists
    return bool(_get_docker().images(name=name))
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/docker.py", line 98, in _get_docker
    api_version = version_client.version()['ApiVersion']
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/docker/api/daemon.py", line 78, in version
    return self._result(self._get(url), json=True)
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/docker/client.py", line 110, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/requests/adapters.py", line 412, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))

----------------------------------------
any ideas?

**Comment by wardi** [comment]
@JackMc @deniszgonjanin ?

**Comment by deniszgonjanin** [comment]
@husker couple of ideas:

- Cisco VPN messes with Virtualbox networking. Since docker works with virtualbox on OSx, this causes docker to die. See: https://github.com/docker/machine/issues/1500
- When switching wifi networks, Virtualbox networking will sometimes die inexplicably. Restarting that virtual machine works well. Try `docker-machine stop dev` & `docker-machine start dev`. Replace `dev` with the name of your VBox machine used for docker.

**Comment by husker** [comment]
thanks @deniszgonjanin  - tried those, unfortunately i'm still having the same issue. i think i'll give it a try on linux - what flavour of linux do you recommend as most compatible?  centos?

**Comment by deniszgonjanin** [comment]
Ubuntu.

By the way, you seem to be getting the error with `datacats open`. That just launches a browser at whatever address your CKAN is. Try opening it manually. Run `datacats info` to find out the url where it's running.

**Comment by husker** [comment]
it seems i get the same error trying to run any datacats commands. 

----------------------------------------
(venv)Jamess-MacBook-Air:bcgov james$ datacats info
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats info

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/cli/main.py", line 96, in main
    opts['--site'] if '--site' in opts else 'primary')
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/environment.py", line 141, in load
    environment_name, data_only)
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/task.py", line 130, in find_environment_dirs
    docker.require_images()
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/docker.py", line 420, in require_images
    if (not image_exists('datacats/web') or
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/docker.py", line 303, in image_exists
    return bool(_get_docker().images(name=name))
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/datacats/docker.py", line 98, in _get_docker
    api_version = version_client.version()['ApiVersion']
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/docker/api/daemon.py", line 78, in version
    return self._result(self._get(url), json=True)
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/docker/client.py", line 110, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/james/bcdc/venv/lib/python2.7/site-packages/requests/adapters.py", line 412, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))

----------------------------------------

**Comment by deniszgonjanin** [comment]
Can you make sure docker is indeed working? `docker ps` should return a list of running containers. Fixing docker would likely solve your problems
