### ISSUE TITLE
persisting reload issue

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#36]
Mostly happens on OSX it seems like (fully 2/3 of our current users are on a Mac)

```
datacats reload
Starting web server at http://boot2docker:5200/ ...
Traceback (most recent call last):
  File "/Users/steph/Documents/Projets/donneesqc/bin/datacats", line 9, in <module>
    load_entry_point('datacats==0.1', 'console_scripts', 'datacats')()
  File "/Users/steph/Documents/Projets/donneesqc/src/datacats/datacats/cli/main.py", line 110, in main
    return command_fn(project, opts)
  File "/Users/steph/Documents/Projets/donneesqc/src/datacats/datacats/cli/manage.py", line 83, in reload_
    project.wait_for_web_available()
  File "/Users/steph/Documents/Projets/donneesqc/src/datacats/datacats/project.py", line 523, in wait_for_web_available
    WEB_START_TIMEOUT_SECONDS):
  File "/Users/steph/Documents/Projets/donneesqc/src/datacats/datacats/network.py", line 36, in wait_for_service_available
    timeout=min(remaining, REQUEST_TIMEOUT_SECONDS))
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/sessions.py", line 448, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/sessions.py", line 554, in send
    r = adapter.send(request, **kwargs)
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/adapters.py", line 359, in send
    timeout=timeout
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 146, in connect
    conn = self._new_conn()
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 125, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/steph/Documents/Projets/donneesqc/lib/python2.7/site-packages/requests/packages/urllib3/util/connection.py", line 87, in create_connection
    raise err
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', error(61, 'Connection refused'))
```

**Comment by wardi** [comment]
closing as inactive, please comment or reopen if this is still an issue
