### ISSUE TITLE
missing plugin on datacats init

### ISSUE THREAD

**Issue by husker** [datacats/datacats#361]
i think my docker networking issues are resolved - now getting a PluginNotFoundException -any suggestions ?:

(dev)james@james-ubuntu:~/projects/bcdc/dev/bcgov$ datacats init
Creating environment bcgov/primary from existing environment directory "bcgov"../home/james/projects/bcdc/dev/local/lib/python2.7/site-packages/docker/utils/utils.py:486: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
....
Installing ckan
Installing ckanext-ga-report
Installing ckanext-geoview
Installing ckanext-googleanalytics
Installing ckanext-hierarchy
Installing ckanext-pdfview
Installing ckanext-scheming
Installing ckanext-spatial
Installing datapusher
Installing edc-idir
Installing edc-rss
Installing ckan requirements
Installing ckanext-ga-report requirements
Installing ckanext-geoview requirements
Installing ckanext-scheming requirements
Installing ckanext-spatial requirements
Installing datapusher requirements
Initializing database----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats init

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/home/james/projects/bcdc/dev/local/lib/python2.7/site-packages/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/home/james/projects/bcdc/dev/local/lib/python2.7/site-packages/datacats/cli/create.py", line 237, in init
    init_db=init_db)
  File "/home/james/projects/bcdc/dev/local/lib/python2.7/site-packages/datacats/cli/create.py", line 257, in finish_init
    environment.ckan_db_init()
  File "/home/james/projects/bcdc/dev/local/lib/python2.7/site-packages/datacats/environment.py", line 354, in ckan_db_init
    clean_up=True,
  File "/home/james/projects/bcdc/dev/local/lib/python2.7/site-packages/datacats/environment.py", line 853, in run_command
    commit=True, stream_output=stream_output)
  File "/home/james/projects/bcdc/dev/local/lib/python2.7/site-packages/datacats/docker.py", line 189, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /usr/lib/ckan/bin/paster --plugin=ckan db init -c /project/development.ini
    Docker Error Log:
    Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/project/ckan/ckan/lib/cli.py", line 208, in command
    self._load_config(cmd!='upgrade')
  File "/project/ckan/ckan/lib/cli.py", line 148, in _load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/project/ckan/ckan/config/environment.py", line 232, in load_environment
    p.load_all(config)
  File "/project/ckan/ckan/plugins/core.py", line 134, in load_all
    load(*plugins)
  File "/project/ckan/ckan/plugins/core.py", line 148, in load
    service = _get_service(plugin)
  File "/project/ckan/ckan/plugins/core.py", line 255, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: edc_dataset

**Comment by deniszgonjanin** [comment]
Make sure you have a copy of `ckanext-bcgov` in your source folder. `edc_dataset` plugin is part of that repo.

**Comment by deniszgonjanin** [comment]
@husker a thing to note is that the `unroll.sh` script in your bcgov repo should have checked out `ckanext-bcgov` from git, but that scripts is very simple and it fails silently. It's just there to help initial setup. Do make sure all of the repository that the `development.ini` depends on are indeed checked out.

**Comment by husker** [comment]
thanks @deniszgonjanin i guess that's the part that's has been failing in the script:
Cloning into 'ckanext-bcgov'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

i'll download the zip and hope that fixes it.

**Comment by deniszgonjanin** [comment]
You could also change the first line of that unroll script from:
```
ckanext-bcgov git@github.com:bcgov/ckanext-bcgov.git master
```

to:
```
https://github.com/bcgov/ckanext-bcgov.git master
```

That should checkout the repo through public means, since that repo is public. Alternatively you can ask B.C. for read/write access to that repo.

**Comment by husker** [comment]
ok thanks @deniszgonjanin  - it is running on ubuntu now! getting some errors, but made some progress- thanks again.

**Comment by deniszgonjanin** [comment]
yay! :smile:
