### ISSUE TITLE
Issues running datacats with old lockfile

### ISSUE THREAD

**Issue by vitorbaptista** [datacats/datacats#367]
It complains about  `from lockfile import LockFile`. The problem is that in my local machine I have a very old `lockfile`, and `datacats` doesn't define a minimum version. I couldn't find the minimum version that datacats works with, but according to their docs at https://pypi.python.org/pypi/lockfile, I would guess `0.9.1` is a good bet.

lockfile is actually deprecated, so depending on how much datacats rely on it, it might be worthy to upgrade.

This is the output I got:

```
vitor@clarisse:~$ sudo pip install datacats                                                                                                                                                                                                    
[sudo] password for vitor: 
The directory '/home/vitor/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/vitor/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting datacats
/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from datacats)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from datacats)
Collecting watchdog (from datacats)
Requirement already satisfied (use --upgrade to upgrade): docker-py>=1.2.1 in /usr/local/lib/python2.7/dist-packages (from datacats)
Requirement already satisfied (use --upgrade to upgrade): docopt in /usr/local/lib/python2.7/dist-packages (from datacats)
Collecting clint (from datacats)
Requirement already satisfied (use --upgrade to upgrade): lockfile in /usr/lib/python2.7/dist-packages (from datacats)
Collecting argh>=0.24.1 (from watchdog->datacats)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in /usr/local/lib/python2.7/dist-packages (from watchdog->datacats)
Collecting pathtools>=0.1.1 (from watchdog->datacats)
Requirement already satisfied (use --upgrade to upgrade): six>=1.3.0 in /usr/local/lib/python2.7/dist-packages (from docker-py>=1.2.1->datacats)
Requirement already satisfied (use --upgrade to upgrade): websocket-client>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker-py>=1.2.1->datacats)
Collecting args (from clint->datacats)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /usr/local/lib/python2.7/dist-packages (from websocket-client>=0.32.0->docker-py>=1.2.1->datacats)
Installing collected packages: argh, pathtools, watchdog, args, clint, datacats
Successfully installed argh-0.26.1 args-0.1.0 clint-0.5.1 datacats-1.2.0 pathtools-0.1.2 watchdog-0.8.3
vitor@clarisse:~$ datacats pull
Traceback (most recent call last):
  File "/usr/local/bin/datacats", line 7, in <module>
    from datacats.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/main.py", line 42, in <module>
    from datacats.cli import (create, manage, install, pull, purge, shell, deploy,
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 10, in <module>
    from datacats.environment import Environment
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 19, in <module>
    from datacats import task, scripts
  File "/usr/local/lib/python2.7/dist-packages/datacats/task.py", line 19, in <module>
    from datacats import docker, validate, migrate
  File "/usr/local/lib/python2.7/dist-packages/datacats/migrate.py", line 12, in <module>
    from lockfile import LockFile
ImportError: cannot import name LockFile
vitor@clarisse:~$ python --version
Python 2.7.6
vitor@clarisse:~$ docker --version
Docker version 1.9.1, build a34a1d5
```

**Comment by JackMc** [comment]
Oh, crud! What is the suggested replacement for lockfile?

**Comment by JackMc** [comment]
We generally use ```datacats``` in a virtualenv, and that's the suggested method of installation, by the way.

**Comment by vitorbaptista** [comment]
From their README:

> Note: This package is **deprecated**. It is highly preferred that instead of
using this code base that instead `fasteners` or `oslo.concurrency` is
used instead.
https://pypi.python.org/pypi/lockfile

I understand that using a virtualenv is the recommended way, and doing it would certainly avoid this bug, but it would still exist.
