### ISSUE TITLE
Error when creating CKAN 2.4 image

### ISSUE THREAD

**Issue by vitorbaptista** [datacats/datacats#368]
I've just installed datacats (version 1.2.0). Created one CKAN image using `datacats create --ckan=master ckandev`, changed my mind and went for a release instead of master and got:

```
vitor@clarisse:~/Projetos/okfn$ datacats create --ckan=2.4 ckan
Creating environment "ckan/primary"...........
Installing ckan
Installing ckanext-ckantheme
Installing datapusher
Installing ckan requirements
Installing datapusher requirements
Initializing database
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create --ckan=2.4 ckan

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 112, in create_environment
    interactive=interactive, init_db=init_db)
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 256, in finish_init
    environment.install_postgis_sql()
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 367, in install_postgis_sql
    links={self._get_container_name('postgres'): 'db'},
  File "/usr/local/lib/python2.7/dist-packages/datacats/docker.py", line 189, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/install_postgis.sh
    Docker Error Log:
    psql: FATAL:  could not open relation mapping file "global/pg_filenode.map": No such file or directory

----------------------------------------
```

**Comment by vitorbaptista** [comment]
This might help:

```
vitor@clarisse:~/Projetos/okfn$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
f411a4fcc845        datacats/web        "/scripts/web.sh Fals"   6 minutes ago       Up 6 minutes        127.0.0.1:5206->5000/tcp   datacats_web_ckan_primary
b330ebeffef6        datacats/web        "/scripts/datapusher."   6 minutes ago       Up 6 minutes        5000/tcp                   datacats_datapusher_ckan_primary
c3c1b784cc63        datacats/solr       "/usr/share/tomcat6/b"   6 minutes ago       Up 6 minutes        8080/tcp                   datacats_solr_ckan_primary
ab8374f02e19        datacats/postgres   "/docker-entrypoint.s"   6 minutes ago       Up 6 minutes        5432/tcp                   datacats_postgres_ckan_primary
```
