### ISSUE TITLE
`--install-postgis` error on clean install

### ISSUE THREAD

**Issue by psigen** [datacats/datacats#376]
I created a new EC2 ubuntu instance with Docker installed.  After checking out a site that includes `ckanext-spatial` as a plugin, I tried to initialize the site:
```
$ pip install --upgrade datacats
$ datacats init --image-only
$ datacats tweak --install-postgis
Installing postgis
/usr/local/lib/python2.7/site-packages/docker/utils/utils.py:591: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats tweak --install-postgis

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/datacats/cli/main.py", line 99, in main
    return command_fn(environment, opts)
  File "/usr/local/lib/python2.7/site-packages/datacats/cli/manage.py", line 291, in tweak
    environment.install_postgis_sql()
  File "/usr/local/lib/python2.7/site-packages/datacats/environment.py", line 367, in install_postgis_sql
    links={self._get_container_name('postgres'): 'db'},
  File "/usr/local/lib/python2.7/site-packages/datacats/docker.py", line 189, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/install_postgis.sh
    Docker Error Log:
     ?column?
----------
        1
(1 row)

/usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql: No such file or directory
```

**Comment by florianm** [comment]
Did you install postgis on that EC2? Something along the lines of `sudo apt-get install postgresql-9.3-postgis-2.1` - just in case datacats looks in the EC2 rather than in the docker container for the postgis scripts. Just a wild guess - HTH!

**Comment by psigen** [comment]
Thanks for the suggestion.  Perhaps I am missing something, but isn't the whole point of a docker containerization of CKAN so that I _don't_ have to install specific versions of `postgresql` and `postgis` onto my host machine?

I have a minimal (non-Ubuntu) OS, and I was planning on moving onto my CoreOS cluster, which is definitely not going to support installing `postgis` on hosts.  Is there some reason this is a host-side dependency here?

In any case, I'll try installing the packages on a fresh Ubuntu VM machine and see if the error is resolved.

**Comment by florianm** [comment]
Agree, shouldn't be necessary on the host. I faintly remember running into this error myself. The solution will be in the datacats issues somewhere if I did.

**Comment by JackMc** [comment]
Hi guys. Try doing this on datacats master, it was fixed by the most recent
commit

**Comment by SaintlyVi** [comment]
Hey!
Did you manage to resolve the issue? I encountered a similar error on a fresh Ubuntu VM. 

`(myckan) wiebke@srvubuerc001:~$ datacats create --ckan latest AERDB
----------------------------------------
datacats: problem was encountered:
Please choose an environment name starting with a letter and including only lowercase letters and digits
----------------------------------------
(myckan) wiebke@srvubuerc001:~$ datacats create --ckan latest aerdb
Creating environment "aerdb/primary"../home/wiebke/myckan/local/lib/python2.7/site-packages/docker/utils/utils.py:591: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
.........
Installing ckan
Installing ckanext-aerdbtheme
Installing datapusher
Installing ckan requirements
Installing datapusher requirements
Initializing database
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create --ckan latest aerdb

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/home/wiebke/myckan/local/lib/python2.7/site-packages/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/home/wiebke/myckan/local/lib/python2.7/site-packages/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/home/wiebke/myckan/local/lib/python2.7/site-packages/datacats/cli/create.py", line 112, in create_environment
    interactive=interactive, init_db=init_db)
  File "/home/wiebke/myckan/local/lib/python2.7/site-packages/datacats/cli/create.py", line 256, in finish_init
    environment.install_postgis_sql()
  File "/home/wiebke/myckan/local/lib/python2.7/site-packages/datacats/environment.py", line 367, in install_postgis_sql
    links={self._get_container_name('postgres'): 'db'},
  File "/home/wiebke/myckan/local/lib/python2.7/site-packages/datacats/docker.py", line 189, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /scripts/install_postgis.sh
    Docker Error Log:
     ?column? 
----------
        1
(1 row)

/usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql: No such file or directory

----------------------------------------
`

**Comment by SaintlyVi** [comment]
Solved with master install...just wasn't sure how to do it initially cause I'm still quite new to this. `datacats pull` keeps failing to pull datacats/web image though, regardless of which install method is used. May just be a temporary error.

**Comment by Kyle-Falconer** [comment]
I could get this to work using the latest code from master and having installed postgresql-9.3-postgis-2.1 on Ubuntu, but this will not work on OS X, even with PostgreSQL installed.
