### ISSUE TITLE
Cannot initialize database on fresh install

### ISSUE THREAD

**Issue by Kyle-Falconer** [datacats/datacats#379]
I'm having a helluva time trying to get this thing to install and run. I first ran into issue #355 which has the solution saying that we should run from development, so I cloned the development version, did `python setup.py develop`, then tried to do the `create` command, and this is what I get now:

Here's the traceback:

```
(venv) vtaisg708384:vta_datacats falconer_k$ datacats create catstown
Creating environment "catstown/primary"../Users/falconer_k/git/vta_datacats/venv/lib/python2.7/site-packages/docker/utils/utils.py:625: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
.........
Installing ckan
Installing ckanext-catstowntheme
Installing datapusher
Installing ckan requirements
Installing datapusher requirements
Initializing database
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create catstown

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/falconer_k/git/vta_datacats/datacats/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/Users/falconer_k/git/vta_datacats/datacats/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/Users/falconer_k/git/vta_datacats/datacats/datacats/cli/create.py", line 112, in create_environment
    interactive=interactive, init_db=init_db)
  File "/Users/falconer_k/git/vta_datacats/datacats/datacats/cli/create.py", line 257, in finish_init
    environment.ckan_db_init()
  File "/Users/falconer_k/git/vta_datacats/datacats/datacats/environment.py", line 354, in ckan_db_init
    clean_up=True,
  File "/Users/falconer_k/git/vta_datacats/datacats/datacats/environment.py", line 853, in run_command
    commit=True, stream_output=stream_output)
  File "/Users/falconer_k/git/vta_datacats/datacats/datacats/docker.py", line 206, in web_command
    raise WebCommandError(command, c['Id'][:12], logs)
WebCommandError:     Command: /usr/lib/ckan/bin/paster --plugin=ckan db init -c /project/development.ini
    Docker Error Log:
    Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/project/ckan/ckan/lib/cli.py", line 207, in command
    self._load_config(cmd!='upgrade')
  File "/project/ckan/ckan/lib/cli.py", line 147, in _load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/project/ckan/ckan/config/environment.py", line 232, in load_environment
    p.load_all(config)
  File "/project/ckan/ckan/plugins/core.py", line 124, in load_all
    unload_all()
  File "/project/ckan/ckan/plugins/core.py", line 181, in unload_all
    unload(*reversed(_PLUGINS))
  File "/project/ckan/ckan/plugins/core.py", line 209, in unload
    plugins_update()
  File "/project/ckan/ckan/plugins/core.py", line 116, in plugins_update
    environment.update_config()
  File "/project/ckan/ckan/config/environment.py", line 400, in update_config
    model.init_model(engine)
  File "/project/ckan/ckan/model/__init__.py", line 183, in init_model
    version_table = Table('migrate_version', meta.metadata, autoload=True)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/schema.py", line 318, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/schema.py", line 381, in _init
    self._autoload(metadata, autoload_with, include_columns)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/schema.py", line 408, in _autoload
    self, include_columns, exclude_columns
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2424, in run_callable
    conn = self.contextual_connect()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2490, in contextual_connect
    self.pool.connect(),
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 224, in connect
    return _ConnectionFairy(self).checkout()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 387, in __init__
    rec = self._connection_record = pool._do_get()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 741, in _do_get
    con = self._create_connection()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 188, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 270, in __init__
    self.connection = self.__connect()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 330, in __connect
    connection = self.__pool._creator()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 281, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 179, in connect
    connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (OperationalError) FATAL:  password authentication failed for user "ckan"
 None None

----------------------------------------
```

**Comment by wardi** [comment]
I'm sorry I can't reproduce this this bug. I've just reinstalled datacats on a clean Ubuntu 16.04 and I get the same warning but it's working fine:
```
$ datacats create catstown
Creating environment "catstown/primary"../home/ian/venv/work/local/lib/python2.7/site-packages/docker_py-1.8.1-py2.7.egg/docker/utils/utils.py:625: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
.........
Installing ckan
Installing ckanext-catstowntheme
Installing datapusher
Installing ckan requirements
Installing datapusher requirements
Initializing database
Starting web server at http://127.0.0.1:5439/ ...
admin user password:
confirm password:
```

I wonder if this is an OSX Docker issue? Afraid I don't have a Mac to investigate.

**Comment by markdturner** [comment]
I also get this bug on OSX. I have been trying to follow the standard documentation but ran into the same problem as #376 so switched to the manual install from source which gets further, but has the same error as described by @Kyle-Falconer

**Comment by markdturner** [comment]
It seems that when the Postgres DB gets setup, the password that gets auto generated is not the same as the one that appears in the passwords.ini file in the data folder. Using the method in #357 of accessing the shell and attempting PSQL commands, I cannot log into the DB using the password from the passwords.ini file.

I'm still hunting through the source code to try and find where Postgres is initialised to see if I can at least hard code a password. 

@Kyle-Falconer have you  managed to get any further with this?

**Comment by wardi** [comment]
the passwords stored are absolutely the ones being used for postgres and the other users, unless there's something really different going on with your environment. If this is OSX and/or new-docker-version-related I'm afraid I can't help because I don't have those things.

**Comment by Kyle-Falconer** [comment]
I've given up on datacats for now because of how it depends on using older versions of Docker (the files reference the docker container, which is no longer needed). It also uses an older version of CKAN.

If this project gets updated, I'll give it another go.
