### ISSUE TITLE
datacats pull errors out on os x latest with virtualenv 2.7

### ISSUE THREAD

**Issue by stevenvandervalk** [datacats/datacats#388]
Hi just reporting this because I'm following http://docs.datacats.com/guide.html#installation and seeing the error below.  Thanks for the project, would love to deploy ckan dockerized.

```
⟩ datacats pull
Pulling image datacats/web...................----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats pull

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/Users/stevenvandervalk/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/Users/stevenvandervalk/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/cli/pull.py", line 46, in pull
    retrying_pull_image(i)
  File "/Users/stevenvandervalk/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/cli/pull.py", line 52, in retrying_pull_image
    "Failed to pull image {}.".format(image_name))
  File "/Users/stevenvandervalk/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/cli/pull.py", line 72, in _retry_func
    func(param)
  File "/Users/stevenvandervalk/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/cli/pull.py", line 83, in pull_image
    for s in pull_stream(image_name):
  File "/Users/stevenvandervalk/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/docker.py", line 386, in <genexpr>
    return (json.loads(s) for s in _get_docker().pull(image, stream=True))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 9 column 1 (char 71 - 568)
```

**Comment by siuying** [comment]
get similar error:

```
ValueError: Extra data: line 2 column 1 - line 16 column 1 (char 71 - 1065)
```

**Comment by wardi** [comment]
Sorry, I don't have a way to debug osx or docker-machine issues. but if you find a fix feel free to submit a PR

**Comment by siuying** [comment]
Hmm, can you advice versions of distro/docker/docker machine/python that datacats supposed to work?

I'd like to evaluate CKAN first before spending time on software that build docker image for CKAN. I'll just create a VM and build a working docker image that runs on any platform.

**Comment by wardi** [comment]
@siuying building a docker image that works on any machine would be great! There has been some recent work in that direction on the main ckan repo https://github.com/ckan/ckan/blob/master/Dockerfile maybe you could help from there? It is being run as an automated build on the docker hub for master but not the stable releases yet.

**Comment by siuying** [comment]
I was just got the impression that the dockerfile there is deprecated and some of the issues pointing datacats as the only way to run it with docker... I have looked at the dockerfile, it had everything:  python apache nginx postfix... I'm no docker expert but that didn't seems right direction.
