### ISSUE TITLE
starting container with HostConfig was deprecated since v1.10 and removed in v1.12

### ISSUE THREAD

**Issue by vladimirghetau** [datacats/datacats#390]
Hi All, 

When I try to get started, I get this error in the title of the issue. It seems docker changed it's api and deprecated some of the endpoints.

----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats create dealx

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/usr/local/lib/python2.7/dist-packages/datacats/cli/create.py", line 104, in create_environment
    fn()
  File "/usr/local/lib/python2.7/dist-packages/datacats/environment.py", line 233, in create_virtualenv
    self._preload_image(), self._get_container_name)
  File "/usr/local/lib/python2.7/dist-packages/datacats/task.py", line 441, in create_virtualenv
    ro={srcdir: '/project'},
  File "/usr/local/lib/python2.7/dist-packages/datacats/docker.py", line 178, in web_command
    volumes_from=volumes_from)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 383, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 400 Client Error: Bad Request ("{"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}")

----------------------------------------

Any advice?

Many thanks!

**Comment by Germanaz0** [comment]
I am getting a very similar error on that, it seems to be almost the same issue, the docker version

```
Traceback (most recent call last):
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/datacats-1.2.0-py2.7.egg/datacats/cli/main.py", line 92, in main
    return command_fn(opts)
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/datacats-1.2.0-py2.7.egg/datacats/cli/create.py", line 62, in create
    init_db=not opts['--no-init-db'],
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/datacats-1.2.0-py2.7.egg/datacats/cli/create.py", line 104, in create_environment
    fn()
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/datacats-1.2.0-py2.7.egg/datacats/environment.py", line 233, in create_virtualenv
    self._preload_image(), self._get_container_name)
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/datacats-1.2.0-py2.7.egg/datacats/task.py", line 441, in create_virtualenv
    ro={srcdir: '/project'},
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/datacats-1.2.0-py2.7.egg/datacats/docker.py", line 195, in web_command
    volumes_from=volumes_from)
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/docker_py-1.10.6-py2.7.egg/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/docker_py-1.10.6-py2.7.egg/docker/api/container.py", line 383, in start
    self._raise_for_status(res)
  File "/mnt/btrfsvol/venvs/ckan/local/lib/python2.7/site-packages/docker_py-1.10.6-py2.7.egg/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 400 Client Error: Bad Request ("{"message":"starting container with non-empty request body was deprecated since v1.10 and removed in v1.12"}")
```

What I am about to do is to downgrade docker, but it seems to not be a good idea.

**Comment by wardi** [comment]
This code is only sporadically maintained right now, so fixes related to supporting docker API changes are welcome but you might be better off contributing to the docker work already in the main CKAN repo.

**Comment by volands** [comment]
Hi,

unfortunately I get the same error - there seems to be problems with newer docker versions, I run:
- Ubuntu LTS 16.04.02
- Docker version 17.03.0-ce, build 60ccb22, API v1.26

There are some "deprecated" binding messages and especially the following error (traceback attached):

> APIError: 400 Client Error: starting container with non-empty request body was deprecated since v1.10 and removed in v1.12

```
(venv) user@energydata:~/energydata.info$ datacats init

/home/user/datacats/venv/local/lib/python2.7/site-packages/docker_py-1.10.6-py2.7.egg/docker/utils/utils.py:618: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
'docker.utils.create_host_config() is deprecated. Please use '
----------------------------------------
datacats: problem was encountered:
Something that should not have happened happened when attempting to run this command:
     datacats reload

It is seems to be a bug.
Please report this issue to us by creating an issue ticket at

    https://github.com/datacats/datacats/issues

so that we would be able to look into that and fix the issue.

------------------------------
Please quote this traceback when reporting this error:
Traceback (most recent call last):
  File "/home/user/datacats/datacats/datacats/cli/main.py", line 99, in main
    return command_fn(environment, opts)
  File "/home/user/datacats/datacats/datacats/cli/manage.py", line 125, in reload_
    environment.start_supporting_containers()
  File "/home/user/datacats/datacats/datacats/environment.py", line 276, in start_supporting_containers
    log_syslog=log_syslog
  File "/home/user/datacats/datacats/datacats/task.py", line 510, in start_supporting_containers
    log_syslog=log_syslog)
  File "/home/user/datacats/datacats/datacats/docker.py", line 296, in run_container
    port_bindings=port_bindings)
  File "/home/user/datacats/venv/local/lib/python2.7/site-packages/docker_py-1.10.6-py2.7.egg/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/user/datacats/venv/local/lib/python2.7/site-packages/docker_py-1.10.6-py2.7.egg/docker/api/container.py", line 383, in start
    self._raise_for_status(res)
  File "/home/user/datacats/venv/local/lib/python2.7/site-packages/docker_py-1.10.6-py2.7.egg/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 400 Client Error: Bad Request ("{"message":"starting container with non-empty request body was deprecated since v1.10 and removed in v1.12"}"
```

Hope you can help in this case or have an idea for solving.

Thanks and best regards,
Patrick
