### ISSUE TITLE
OpenSSL / Requests Issues on datacats pull

### ISSUE THREAD

**Issue by scuerda** [datacats/datacats#63]
Using boot2docker on OSX 10.10.1 with Homebrew

Seems related to #38 and/or #61, but not resolved by either. Might be related to issues with pyopenssl discussed https://github.com/CI-WATER/tethys/issues/50 and https://github.com/Homebrew/homebrew/issues/38226.

I was having some seemingly unrelated homebrew issues and issues discussed here: https://github.com/docker/compose/issues/890 seem like they might be fruitful.

Here is traceback.

I'll update if I find a solution.

```
Pulling image datacats/webTraceback (most recent call last):
  File "/usr/local/bin/datacats", line 9, in <module>
    load_entry_point('datacats==0.8', 'console_scripts', 'datacats')()
  File "/usr/local/lib/python2.7/site-packages/datacats/cli/main.py", line 116, in main
    return command_fn(opts)
  File "/usr/local/lib/python2.7/site-packages/datacats/cli/pull.py", line 30, in pull
    for s in pull_stream(i):
  File "/usr/local/lib/python2.7/site-packages/datacats/docker.py", line 199, in pull_stream
    return (json.loads(s) for s in _docker.pull(image, stream=True))
  File "/Library/Python/2.7/site-packages/docker/client.py", line 772, in pull
    headers=headers, stream=stream, timeout=None)
  File "/Library/Python/2.7/site-packages/docker/client.py", line 100, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 272, in ssl_wrap_socket
    ctx = OpenSSL.SSL.Context(_openssl_versions[ssl_version])
```

**Comment by stevemolitor** [comment]
Hey we're seeing the same thing on a few developer boxes as well when running `docker-compose run <name> <command>`. Here is the stacktrace, this with boot2docker 1.5.0 and docker-compose 1.1.0 on OSX 10.10.2.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/fig/1.1.0/libexec/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.1.0', 'console_scripts', 'docker-compose')()
  File "/usr/local/Cellar/fig/1.1.0/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/usr/local/Cellar/fig/1.1.0/libexec/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/Cellar/fig/1.1.0/libexec/lib/python2.7/site-packages/compose/cli/command.py", line 27, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/local/Cellar/fig/1.1.0/libexec/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/Cellar/fig/1.1.0/libexec/lib/python2.7/site-packages/compose/cli/command.py", line 59, in perform_command
    handler(project, command_options)
  File "/usr/local/Cellar/fig/1.1.0/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 341, in run
    dockerpty.start(project.client, container.id, interactive=not options['-T'])
  File "/usr/local/Cellar/fig/1.1.0/libexec/vendor/lib/python2.7/site-packages/dockerpty/__init__.py", line 27, in start
    PseudoTerminal(client, container, interactive=interactive).start()
  File "/usr/local/Cellar/fig/1.1.0/libexec/vendor/lib/python2.7/site-packages/dockerpty/pty.py", line 151, in start
    self._hijack_tty(pumps)
  File "/usr/local/Cellar/fig/1.1.0/libexec/vendor/lib/python2.7/site-packages/dockerpty/pty.py", line 235, in _hijack_tty
    if any([p.flush() is None for p in ready]):
  File "/usr/local/Cellar/fig/1.1.0/libexec/vendor/lib/python2.7/site-packages/dockerpty/io.py", line 285, in flush
    return self.to_stream.write(self.from_stream.read(n))
  File "/usr/local/Cellar/fig/1.1.0/libexec/vendor/lib/python2.7/site-packages/dockerpty/io.py", line 119, in read
    return self.fd.recv(n)
  File "/usr/local/Cellar/fig/1.1.0/libexec/vendor/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 183, in recv
    data = self.connection.recv(*args, **kwargs)
OpenSSL.SSL.ZeroReturnError

```

**Comment by stevemolitor** [comment]
Another note, we tried with both brew and pip based installs, the same issue occurred.

**Comment by JackMc** [comment]
Unfortunately the only solution that I have found to these kinds of issues is to disable TLS as follows:

```
$ boot2docker ssh
docker@boot2docker:~$ sudo vi /var/lib/boot2docker/profile
```

and putting the line ``DOCKER_TLS=no`` in that file.

**Comment by dborzov** [comment]
Here is a helpful discussion of this issue: [docker/docker-py/issues/465](https://github.com/docker/docker-py/issues/465)

The solution that worked for me was switching to the older version of openssl via brew:
```
   brew switch openssl 1.0.1j_1
```

**Comment by wardi** [comment]
workaround in #143 when the upstream openssl libraries are fixed and verified to work we can remove this workaround.
