### ISSUE TITLE
When things go wrong, path to recovery is often unclear

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#64]
For example, a boot2docker VM dies. Upon recovery, doing `datacats start` on a project will show:
```
Traceback (most recent call last):
  File "/Users/dz/Envs/datacats/bin/datacats", line 9, in <module>
    load_entry_point('datacats==0.9dev1', 'console_scripts', 'datacats')()
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/datacats-0.9dev1-py2.7.egg/datacats/cli/main.py", line 115, in main
    return command_fn(project, opts)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/datacats-0.9dev1-py2.7.egg/datacats/cli/manage.py", line 54, in start
    reload_(project, opts)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/datacats-0.9dev1-py2.7.egg/datacats/cli/manage.py", line 80, in reload_
    project.start_web(opts['--production'])
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/datacats-0.9dev1-py2.7.egg/datacats/project.py", line 502, in start_web
    self._run_web_container(port, command)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/datacats-0.9dev1-py2.7.egg/datacats/project.py", line 571, in _run_web_container
    5000: port if is_boot2docker() else ('127.0.0.1', port)},
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/datacats-0.9dev1-py2.7.egg/datacats/docker.py", line 157, in run_container
    port_bindings=port_bindings)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.1.0-py2.7.egg/docker/client.py", line 904, in start
    self._raise_for_status(res)
  File "/Users/dz/Envs/datacats/lib/python2.7/site-packages/docker_py-1.1.0-py2.7.egg/docker/client.py", line 119, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 406 Client Error: Not Acceptable ("Cannot start container 4e5e47801f4201c0365ce5b363263e27e7576480259289f7f7bbc8a84867932e: container datacats_venv_donneesqc not found, impossible to mount its volumes")
```

The correct path to recovery is to do:
```
datacats purge
datacats init
```

But this is not clear. Easiest thing to do would be to output a message if this error is caught, to the effect of: "If your volume containers were deleted, for example if your boot2docker VM died, run `datacats purge` followed by `datacats init` in order to recover"

**Comment by deniszgonjanin** [comment]
Another example of this issue, when #83 happens:
```
datacats purge ckantest --delete-environment
Traceback (most recent call last):
  File "/home/sshadmin/.virtualenvs/datacats/bin/datacats", line 8, in <module>
    load_entry_point('datacats==0.9.2', 'console_scripts', 'datacats')()
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/cli/main.py", line 115, in main
    return command_fn(opts)
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/cli/purge.py", line 25, in purge
    environment = Environment.load(opts['ENVIRONMENT'])
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/environment.py", line 166, in load
    with open(datadir + '/project-dir') as pd:
IOError: [Errno 2] No such file or directory: '/home/sshadmin/.datacats/ckantest/project-dir'
```

**Comment by JackMc** [comment]
#130 fixes the first issue pointed out in this issue.

**Comment by JackMc** [comment]
In the second case there, I suppose the datadir had been deleted?

**Comment by deniszgonjanin** [comment]
In the seconds I don't remember what happened. It could be that boot2docker died and I had to delete it and start a new one. That might be a possible use case to test recovery from

**Comment by dborzov** [comment]
This issue's ambiguiously general title reminds me of this web comic's name:  [www.alessonislearned.com](http://www.alessonislearned.com/)

**Comment by JackMc** [comment]
Heh :smile:

**Comment by wardi** [comment]
close as "too philosophical"?

**Comment by wardi** [comment]
closing because I believe this has been addressed in a number of the recent changes to error messages and how we connect to docker. (If I'm wrong please open again)
