### ISSUE TITLE
Permissions errors on CentOS

### ISSUE THREAD

**Issue by deniszgonjanin** [datacats/datacats#83]
CentOS release 6.6 (Final)
Docker version 1.5.0, build a8a31ef/1.5.0
datacats 0.9.2

```
Creating environment "ckantest4"..........Traceback (most recent call last):
  File "/home/sshadmin/.virtualenvs/datacats/bin/datacats", line 8, in <module>
    load_entry_point('datacats==0.9.2', 'console_scripts', 'datacats')()
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/cli/main.py", line 115, in main
    return command_fn(opts)
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/cli/create.py", line 41, in create
    ckan_version=opts['--ckan'],
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/cli/create.py", line 78, in create_environment
    fn()
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/environment.py", line 445, in create_install_template_skin
    self.install_package_develop('ckanext-' + self.name + 'theme')
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/environment.py", line 773, in install_package_develop
    rw_project=True,
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/environment.py", line 786, in user_run_script
    script: '/scripts/run.sh',
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/environment.py", line 818, in run_command
    volumes_from=volumes_from, clean_up=clean_up)
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/datacats/docker.py", line 114, in web_command
    volumes_from=volumes_from)
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/docker/client.py", line 1063, in start
    self._raise_for_status(res)
  File "/home/sshadmin/.virtualenvs/datacats/lib/python2.7/site-packages/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot start container fed69b7866fcb248f9841cd4c1558acb50d0b165f05b8d38066157ec5a9466a6: exec: "/scripts/run_as_user.sh": permission denied")
```

Adding +x to all scripts in datacats/scripts fixes the issue. I'm not sure why this would happen on CentOS only

**Comment by wardi** [comment]
@deniszgonjanin is the pip install installing files without the executable bit set? All those scripts are marked +x in the repo.  i.e. does it work if you git clone and setup.py develop?

**Comment by deniszgonjanin** [comment]
The weird thing is that I tried this on a CentOS local VM and it worked fine, even when I used pip to install.

**Comment by wardi** [comment]
Is selinux involved somehow?

**Comment by deniszgonjanin** [comment]
Of course it is

**Comment by JackMc** [comment]
We need to resolve this more permanently. Is there anything we can do to, say, tell an SELinux user that they need to set up capabilities (or whatever the term is for SELinux's "permissions") on the scripts in the "scripts" directory?
